// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\nco\nco.v
// Created: 2023-09-15 20:20:03
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0
// Target subsystem base rate: 0
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1                          ce_out        0
// Out2                          ce_out        0
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: nco
// Source Path: nco
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module nco
          (clk,
           reset,
           clk_enable,
           Input_rsvd,
           ce_out,
           Out1,
           Out2);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [15:0] Input_rsvd;  // uint16
  output  ce_out;
  output  signed [11:0] Out1;  // sfix12_En13
  output  Out2;


  wire signed [11:0] Subsystem_out1;  // sfix12_En13
  wire Subsystem_out2;


  Subsystem u_Subsystem (.clk(clk),
                         .reset(reset),
                         .enb(clk_enable),
                         .In1(Input_rsvd),  // uint16
                         .Out1(Subsystem_out1),  // sfix12_En13
                         .Out2(Subsystem_out2)
                         );

  assign Out1 = Subsystem_out1;

  assign Out2 = Subsystem_out2;

  assign ce_out = clk_enable;

endmodule  // nco

