// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\test1\FirRdyLogic.v
// Created: 2023-10-04 18:26:37
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FirRdyLogic
// Source Path: test1/myCNT09/Discrete FIR Filter/FirRdyLogic
// Hierarchy Level: 2
// Model version: 1.17
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FirRdyLogic
          (clk,
           reset,
           enb,
           dinSwitch,
           dinVldSwitch,
           coeff,
           haltProcess,
           readySM,
           dinSM,
           dinVldSM);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dinSwitch;  // sfix16_En15
  input   dinVldSwitch;
  input   signed [15:0] coeff;  // sfix16_En15
  input   haltProcess;
  output  readySM;
  output  signed [15:0] dinSM;  // sfix16_En15
  output  dinVldSM;


  wire syncReset;
  reg signed [15:0] firRdy_xdin;  // sfix16
  reg  firRdy_xdinVld;
  reg [2:0] firRdy_state;  // ufix3
  reg  firRdy_readyReg;
  reg [3:0] firRdy_count;  // ufix4
  reg signed [15:0] firRdy_xcoeffin;  // sfix16
  reg signed [15:0] firRdy_xdin_next;  // sfix16_En15
  reg  firRdy_xdinVld_next;
  reg [2:0] firRdy_state_next;  // ufix3
  reg  firRdy_readyReg_next;
  reg [3:0] firRdy_count_next;  // ufix4
  reg signed [15:0] firRdy_xcoeffin_next;  // sfix16_En15
  reg  readySM_1;
  reg signed [15:0] dinSM_1;  // sfix16_En15
  reg  dinVldSM_1;
  reg signed [15:0] coeffS;  // sfix16_En15
  reg  firRdy_out2_0;


  assign syncReset = 1'b0;



  // rdyLogic
  always @(posedge clk or posedge reset)
    begin : firRdy_process
      if (reset == 1'b1) begin
        firRdy_state <= 3'b000;
        firRdy_xdin <= 16'sb0000000000000000;
        firRdy_xdinVld <= 1'b0;
        firRdy_xcoeffin <= 16'sb0000000000000000;
        firRdy_readyReg <= 1'b1;
        firRdy_count <= 4'b0000;
      end
      else begin
        if (enb) begin
          firRdy_xdin <= firRdy_xdin_next;
          firRdy_xdinVld <= firRdy_xdinVld_next;
          firRdy_state <= firRdy_state_next;
          firRdy_readyReg <= firRdy_readyReg_next;
          firRdy_count <= firRdy_count_next;
          firRdy_xcoeffin <= firRdy_xcoeffin_next;
        end
      end
    end

  always @(coeff, dinSwitch, dinVldSwitch, firRdy_count, firRdy_readyReg, firRdy_state,
       firRdy_xcoeffin, firRdy_xdin, firRdy_xdinVld, haltProcess, syncReset) begin
    firRdy_xdin_next = firRdy_xdin;
    firRdy_xdinVld_next = firRdy_xdinVld;
    firRdy_state_next = firRdy_state;
    firRdy_readyReg_next = firRdy_readyReg;
    firRdy_count_next = firRdy_count;
    firRdy_xcoeffin_next = firRdy_xcoeffin;
    if (( ! haltProcess) && ( ! syncReset)) begin
      case ( firRdy_state)
        3'b000 :
          begin
            dinSM_1 = dinSwitch;
            firRdy_out2_0 = dinVldSwitch;
            coeffS = coeff;
            firRdy_state_next = 3'b000;
            firRdy_readyReg_next = 1'b1;
            firRdy_xdin_next = 16'sb0000000000000000;
            firRdy_xdinVld_next = 1'b0;
            firRdy_xcoeffin_next = 16'sb0000000000000000;
            if (dinVldSwitch) begin
              firRdy_state_next = 3'b001;
              firRdy_readyReg_next = 1'b0;
            end
          end
        3'b001 :
          begin
            dinSM_1 = 16'sb0000000000000000;
            firRdy_out2_0 = 1'b0;
            coeffS = 16'sb0000000000000000;
            firRdy_state_next = 3'b011;
            if (dinVldSwitch) begin
              firRdy_state_next = 3'b010;
              firRdy_xdin_next = dinSwitch;
              firRdy_xdinVld_next = 1'b1;
              firRdy_xcoeffin_next = coeff;
            end
          end
        3'b010 :
          begin
            dinSM_1 = 16'sb0000000000000000;
            firRdy_out2_0 = 1'b0;
            coeffS = 16'sb0000000000000000;
            firRdy_state_next = 3'b010;
            if (firRdy_count == 4'b1001) begin
              firRdy_state_next = 3'b100;
            end
            firRdy_readyReg_next = 1'b0;
          end
        3'b011 :
          begin
            if (firRdy_count == 4'b1001) begin
              firRdy_readyReg_next = 1'b1;
              firRdy_state_next = 3'b000;
            end
            dinSM_1 = 16'sb0000000000000000;
            coeffS = 16'sb0000000000000000;
            firRdy_out2_0 = 1'b0;
          end
        3'b100 :
          begin
            firRdy_state_next = 3'b011;
            dinSM_1 = firRdy_xdin;
            firRdy_out2_0 = firRdy_xdinVld;
            coeffS = firRdy_xcoeffin;
            firRdy_xdin_next = dinSwitch;
            firRdy_xdinVld_next = dinVldSwitch;
            firRdy_xcoeffin_next = coeff;
          end
        default :
          begin
            dinSM_1 = 16'sb0000000000000000;
            firRdy_out2_0 = 1'b0;
            coeffS = 16'sb0000000000000000;
            firRdy_state_next = 3'b000;
            firRdy_xdin_next = 16'sb0000000000000000;
            firRdy_xdinVld_next = 1'b0;
            firRdy_xcoeffin_next = 16'sb0000000000000000;
            firRdy_readyReg_next = 1'b1;
          end
      endcase
    end
    else begin
      firRdy_state_next = 3'b000;
      firRdy_xdin_next = 16'sb0000000000000000;
      firRdy_xcoeffin_next = 16'sb0000000000000000;
      firRdy_xdinVld_next = 1'b0;
      firRdy_readyReg_next = 1'b0;
      dinSM_1 = 16'sb0000000000000000;
      firRdy_out2_0 = 1'b0;
      coeffS = 16'sb0000000000000000;
    end
    if ((dinVldSwitch || (firRdy_count > 4'b0000)) || firRdy_out2_0) begin
      if (((firRdy_count == 4'b1001) || haltProcess) || syncReset) begin
        firRdy_count_next = 4'b0000;
      end
      else begin
        firRdy_count_next = firRdy_count + 4'b0001;
      end
    end
    readySM_1 = firRdy_readyReg;
    dinVldSM_1 = firRdy_out2_0;
  end



  assign readySM = readySM_1;

  assign dinSM = dinSM_1;

  assign dinVldSM = dinVldSM_1;

endmodule  // FirRdyLogic

