// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\FPGA_myself\DDS\I2S\REC_I2S\hdlsrc\rec_i2s\SIPO_4BIT_block.v
// Created: 2023-10-27 21:14:54
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SIPO_4BIT_block
// Source Path: rec_i2s/REC_I2S/SIPO_32BIT_R/Subsystem/SIPO_16BIT/SIPO_8BIT1/SIPO_4BIT
// Hierarchy Level: 6
// Model version: 1.39
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SIPO_4BIT_block
          (clk,
           reset,
           enb,
           SERIAL_IN,
           PARA_OUT_0,
           PARA_OUT_1,
           PARA_OUT_2,
           PARA_OUT_3,
           SERIAL_OUT);


  input   clk;
  input   reset;
  input   enb;
  input   SERIAL_IN;
  output  PARA_OUT_0;  // boolean
  output  PARA_OUT_1;  // boolean
  output  PARA_OUT_2;  // boolean
  output  PARA_OUT_3;  // boolean
  output  SERIAL_OUT;


  wire alpha2BIT_SIPO_out1_0;
  wire alpha2BIT_SIPO_out1_1;
  wire alpha2BIT_SIPO_out2;
  wire alpha2BIT_SIPO1_out1_0;
  wire alpha2BIT_SIPO1_out1_1;
  wire alpha2BIT_SIPO1_out2;


  alpha2BIT_SIPO_block1 u_2BIT_SIPO (.clk(clk),
                                     .reset(reset),
                                     .enb(enb),
                                     .SERIAL_IN(SERIAL_IN),
                                     .PARA_OUT_0(alpha2BIT_SIPO_out1_0),  // boolean
                                     .PARA_OUT_1(alpha2BIT_SIPO_out1_1),  // boolean
                                     .SERIAL_OUT(alpha2BIT_SIPO_out2)
                                     );

  alpha2BIT_SIPO1_block1 u_2BIT_SIPO1 (.clk(clk),
                                       .reset(reset),
                                       .enb(enb),
                                       .SERIAL_IN(alpha2BIT_SIPO_out2),
                                       .PARA_OUT_0(alpha2BIT_SIPO1_out1_0),  // boolean
                                       .PARA_OUT_1(alpha2BIT_SIPO1_out1_1),  // boolean
                                       .SERIAL_OUT(alpha2BIT_SIPO1_out2)
                                       );

  assign PARA_OUT_0 = alpha2BIT_SIPO1_out1_0;

  assign PARA_OUT_1 = alpha2BIT_SIPO1_out1_1;

  assign PARA_OUT_2 = alpha2BIT_SIPO_out1_0;

  assign PARA_OUT_3 = alpha2BIT_SIPO_out1_1;

  assign SERIAL_OUT = alpha2BIT_SIPO1_out2;

endmodule  // SIPO_4BIT_block

