// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\FPGA_myself\DDS\I2S\REC_I2S\hdlsrc\rec_i2s\SIPO_8BIT.v
// Created: 2023-10-27 21:14:54
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SIPO_8BIT
// Source Path: rec_i2s/REC_I2S/SIPO_32BIT_R/Subsystem/SIPO_16BIT/SIPO_8BIT
// Hierarchy Level: 5
// Model version: 1.39
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SIPO_8BIT
          (clk,
           reset,
           enb,
           SERIAL_IN,
           PARA_OUT_0,
           PARA_OUT_1,
           PARA_OUT_2,
           PARA_OUT_3,
           PARA_OUT_4,
           PARA_OUT_5,
           PARA_OUT_6,
           PARA_OUT_7,
           SERIAL_OUT);


  input   clk;
  input   reset;
  input   enb;
  input   SERIAL_IN;
  output  PARA_OUT_0;  // boolean
  output  PARA_OUT_1;  // boolean
  output  PARA_OUT_2;  // boolean
  output  PARA_OUT_3;  // boolean
  output  PARA_OUT_4;  // boolean
  output  PARA_OUT_5;  // boolean
  output  PARA_OUT_6;  // boolean
  output  PARA_OUT_7;  // boolean
  output  SERIAL_OUT;


  wire SIPO_4BIT_out1_0;
  wire SIPO_4BIT_out1_1;
  wire SIPO_4BIT_out1_2;
  wire SIPO_4BIT_out1_3;
  wire SIPO_4BIT_out2;
  wire SIPO_4BIT1_out1_0;
  wire SIPO_4BIT1_out1_1;
  wire SIPO_4BIT1_out1_2;
  wire SIPO_4BIT1_out1_3;
  wire SIPO_4BIT1_out2;


  SIPO_4BIT u_SIPO_4BIT (.clk(clk),
                         .reset(reset),
                         .enb(enb),
                         .SERIAL_IN(SERIAL_IN),
                         .PARA_OUT_0(SIPO_4BIT_out1_0),  // boolean
                         .PARA_OUT_1(SIPO_4BIT_out1_1),  // boolean
                         .PARA_OUT_2(SIPO_4BIT_out1_2),  // boolean
                         .PARA_OUT_3(SIPO_4BIT_out1_3),  // boolean
                         .SERIAL_OUT(SIPO_4BIT_out2)
                         );

  SIPO_4BIT1 u_SIPO_4BIT1 (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .SERIAL_IN(SIPO_4BIT_out2),
                           .PARA_OUT_0(SIPO_4BIT1_out1_0),  // boolean
                           .PARA_OUT_1(SIPO_4BIT1_out1_1),  // boolean
                           .PARA_OUT_2(SIPO_4BIT1_out1_2),  // boolean
                           .PARA_OUT_3(SIPO_4BIT1_out1_3),  // boolean
                           .SERIAL_OUT(SIPO_4BIT1_out2)
                           );

  assign PARA_OUT_0 = SIPO_4BIT1_out1_0;

  assign PARA_OUT_1 = SIPO_4BIT1_out1_1;

  assign PARA_OUT_2 = SIPO_4BIT1_out1_2;

  assign PARA_OUT_3 = SIPO_4BIT1_out1_3;

  assign PARA_OUT_4 = SIPO_4BIT_out1_0;

  assign PARA_OUT_5 = SIPO_4BIT_out1_1;

  assign PARA_OUT_6 = SIPO_4BIT_out1_2;

  assign PARA_OUT_7 = SIPO_4BIT_out1_3;

  assign SERIAL_OUT = SIPO_4BIT1_out2;

endmodule  // SIPO_8BIT

