-- -------------------------------------------------------------
-- 
-- File Name: F:\Git_Repository\FPGA_myself\DDS\DDS_CSDN\DDS_32BIT\hdlsrc\NCO\FilterCoef.vhd
-- Created: 2023-09-22 17:10:45
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FilterCoef
-- Source Path: NCO/Subsystem/Discrete FIR Filter/Filter/FilterCoef
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.NCO_pkg.ALL;

ENTITY FilterCoef IS
  PORT( CoefOut                           :   OUT   vector_of_std_logic_vector16(0 TO 79)  -- sfix16_En17 [80]
        );
END FilterCoef;


ARCHITECTURE rtl OF FilterCoef IS

  -- Signals
  SIGNAL CoefData                         : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_1                       : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_2                       : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_3                       : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_4                       : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_5                       : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_6                       : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_7                       : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_8                       : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_9                       : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_10                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_11                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_12                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_13                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_14                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_15                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_16                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_17                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_18                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_19                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_20                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_21                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_22                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_23                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_24                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_25                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_26                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_27                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_28                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_29                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_30                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_31                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_32                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_33                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_34                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_35                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_36                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_37                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_38                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_39                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_40                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_41                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_42                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_43                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_44                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_45                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_46                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_47                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_48                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_49                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_50                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_51                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_52                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_53                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_54                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_55                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_56                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_57                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_58                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_59                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_60                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_61                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_62                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_63                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_64                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_65                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_66                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_67                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_68                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_69                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_70                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_71                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_72                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_73                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_74                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_75                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_76                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_77                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_78                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_79                      : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefOut_tmp                      : vector_of_signed16(0 TO 79);  -- sfix16_En17 [80]

BEGIN
  -- CoefReg_1
  CoefData <= to_signed(-16#0009#, 16);

  -- CoefReg_2
  CoefData_1 <= to_signed(-16#0017#, 16);

  -- CoefReg_3
  CoefData_2 <= to_signed(-16#001F#, 16);

  -- CoefReg_4
  CoefData_3 <= to_signed(-16#001C#, 16);

  -- CoefReg_5
  CoefData_4 <= to_signed(-16#000A#, 16);

  -- CoefReg_6
  CoefData_5 <= to_signed(16#0016#, 16);

  -- CoefReg_7
  CoefData_6 <= to_signed(16#003C#, 16);

  -- CoefReg_8
  CoefData_7 <= to_signed(16#0058#, 16);

  -- CoefReg_9
  CoefData_8 <= to_signed(16#0053#, 16);

  -- CoefReg_10
  CoefData_9 <= to_signed(16#0020#, 16);

  -- CoefReg_11
  CoefData_10 <= to_signed(-16#003F#, 16);

  -- CoefReg_12
  CoefData_11 <= to_signed(-16#00AC#, 16);

  -- CoefReg_13
  CoefData_12 <= to_signed(-16#00F5#, 16);

  -- CoefReg_14
  CoefData_13 <= to_signed(-16#00E3#, 16);

  -- CoefReg_15
  CoefData_14 <= to_signed(-16#0058#, 16);

  -- CoefReg_16
  CoefData_15 <= to_signed(16#0099#, 16);

  -- CoefReg_17
  CoefData_16 <= to_signed(16#01A1#, 16);

  -- CoefReg_18
  CoefData_17 <= to_signed(16#0245#, 16);

  -- CoefReg_19
  CoefData_18 <= to_signed(16#0210#, 16);

  -- CoefReg_20
  CoefData_19 <= to_signed(16#00CE#, 16);

  -- CoefReg_21
  CoefData_20 <= to_signed(-16#0144#, 16);

  -- CoefReg_22
  CoefData_21 <= to_signed(-16#0372#, 16);

  -- CoefReg_23
  CoefData_22 <= to_signed(-16#04BE#, 16);

  -- CoefReg_24
  CoefData_23 <= to_signed(-16#0446#, 16);

  -- CoefReg_25
  CoefData_24 <= to_signed(-16#01B3#, 16);

  -- CoefReg_26
  CoefData_25 <= to_signed(16#0272#, 16);

  -- CoefReg_27
  CoefData_26 <= to_signed(16#06C2#, 16);

  -- CoefReg_28
  CoefData_27 <= to_signed(16#0954#, 16);

  -- CoefReg_29
  CoefData_28 <= to_signed(16#0878#, 16);

  -- CoefReg_30
  CoefData_29 <= to_signed(16#037E#, 16);

  -- CoefReg_31
  CoefData_30 <= to_signed(-16#04B2#, 16);

  -- CoefReg_32
  CoefData_31 <= to_signed(-16#0D85#, 16);

  -- CoefReg_33
  CoefData_32 <= to_signed(-16#134E#, 16);

  -- CoefReg_34
  CoefData_33 <= to_signed(-16#1259#, 16);

  -- CoefReg_35
  CoefData_34 <= to_signed(-16#083D#, 16);

  -- CoefReg_36
  CoefData_35 <= to_signed(16#0B18#, 16);

  -- CoefReg_37
  CoefData_36 <= to_signed(16#24F3#, 16);

  -- CoefReg_38
  CoefData_37 <= to_signed(16#4059#, 16);

  -- CoefReg_39
  CoefData_38 <= to_signed(16#5741#, 16);

  -- CoefReg_40
  CoefData_39 <= to_signed(16#644B#, 16);

  -- CoefReg_41
  CoefData_40 <= to_signed(16#644B#, 16);

  -- CoefReg_42
  CoefData_41 <= to_signed(16#5741#, 16);

  -- CoefReg_43
  CoefData_42 <= to_signed(16#4059#, 16);

  -- CoefReg_44
  CoefData_43 <= to_signed(16#24F3#, 16);

  -- CoefReg_45
  CoefData_44 <= to_signed(16#0B18#, 16);

  -- CoefReg_46
  CoefData_45 <= to_signed(-16#083D#, 16);

  -- CoefReg_47
  CoefData_46 <= to_signed(-16#1259#, 16);

  -- CoefReg_48
  CoefData_47 <= to_signed(-16#134E#, 16);

  -- CoefReg_49
  CoefData_48 <= to_signed(-16#0D85#, 16);

  -- CoefReg_50
  CoefData_49 <= to_signed(-16#04B2#, 16);

  -- CoefReg_51
  CoefData_50 <= to_signed(16#037E#, 16);

  -- CoefReg_52
  CoefData_51 <= to_signed(16#0878#, 16);

  -- CoefReg_53
  CoefData_52 <= to_signed(16#0954#, 16);

  -- CoefReg_54
  CoefData_53 <= to_signed(16#06C2#, 16);

  -- CoefReg_55
  CoefData_54 <= to_signed(16#0272#, 16);

  -- CoefReg_56
  CoefData_55 <= to_signed(-16#01B3#, 16);

  -- CoefReg_57
  CoefData_56 <= to_signed(-16#0446#, 16);

  -- CoefReg_58
  CoefData_57 <= to_signed(-16#04BE#, 16);

  -- CoefReg_59
  CoefData_58 <= to_signed(-16#0372#, 16);

  -- CoefReg_60
  CoefData_59 <= to_signed(-16#0144#, 16);

  -- CoefReg_61
  CoefData_60 <= to_signed(16#00CE#, 16);

  -- CoefReg_62
  CoefData_61 <= to_signed(16#0210#, 16);

  -- CoefReg_63
  CoefData_62 <= to_signed(16#0245#, 16);

  -- CoefReg_64
  CoefData_63 <= to_signed(16#01A1#, 16);

  -- CoefReg_65
  CoefData_64 <= to_signed(16#0099#, 16);

  -- CoefReg_66
  CoefData_65 <= to_signed(-16#0058#, 16);

  -- CoefReg_67
  CoefData_66 <= to_signed(-16#00E3#, 16);

  -- CoefReg_68
  CoefData_67 <= to_signed(-16#00F5#, 16);

  -- CoefReg_69
  CoefData_68 <= to_signed(-16#00AC#, 16);

  -- CoefReg_70
  CoefData_69 <= to_signed(-16#003F#, 16);

  -- CoefReg_71
  CoefData_70 <= to_signed(16#0020#, 16);

  -- CoefReg_72
  CoefData_71 <= to_signed(16#0053#, 16);

  -- CoefReg_73
  CoefData_72 <= to_signed(16#0058#, 16);

  -- CoefReg_74
  CoefData_73 <= to_signed(16#003C#, 16);

  -- CoefReg_75
  CoefData_74 <= to_signed(16#0016#, 16);

  -- CoefReg_76
  CoefData_75 <= to_signed(-16#000A#, 16);

  -- CoefReg_77
  CoefData_76 <= to_signed(-16#001C#, 16);

  -- CoefReg_78
  CoefData_77 <= to_signed(-16#001F#, 16);

  -- CoefReg_79
  CoefData_78 <= to_signed(-16#0017#, 16);

  -- CoefReg_80
  CoefData_79 <= to_signed(-16#0009#, 16);

  CoefOut_tmp(0) <= CoefData;
  CoefOut_tmp(1) <= CoefData_1;
  CoefOut_tmp(2) <= CoefData_2;
  CoefOut_tmp(3) <= CoefData_3;
  CoefOut_tmp(4) <= CoefData_4;
  CoefOut_tmp(5) <= CoefData_5;
  CoefOut_tmp(6) <= CoefData_6;
  CoefOut_tmp(7) <= CoefData_7;
  CoefOut_tmp(8) <= CoefData_8;
  CoefOut_tmp(9) <= CoefData_9;
  CoefOut_tmp(10) <= CoefData_10;
  CoefOut_tmp(11) <= CoefData_11;
  CoefOut_tmp(12) <= CoefData_12;
  CoefOut_tmp(13) <= CoefData_13;
  CoefOut_tmp(14) <= CoefData_14;
  CoefOut_tmp(15) <= CoefData_15;
  CoefOut_tmp(16) <= CoefData_16;
  CoefOut_tmp(17) <= CoefData_17;
  CoefOut_tmp(18) <= CoefData_18;
  CoefOut_tmp(19) <= CoefData_19;
  CoefOut_tmp(20) <= CoefData_20;
  CoefOut_tmp(21) <= CoefData_21;
  CoefOut_tmp(22) <= CoefData_22;
  CoefOut_tmp(23) <= CoefData_23;
  CoefOut_tmp(24) <= CoefData_24;
  CoefOut_tmp(25) <= CoefData_25;
  CoefOut_tmp(26) <= CoefData_26;
  CoefOut_tmp(27) <= CoefData_27;
  CoefOut_tmp(28) <= CoefData_28;
  CoefOut_tmp(29) <= CoefData_29;
  CoefOut_tmp(30) <= CoefData_30;
  CoefOut_tmp(31) <= CoefData_31;
  CoefOut_tmp(32) <= CoefData_32;
  CoefOut_tmp(33) <= CoefData_33;
  CoefOut_tmp(34) <= CoefData_34;
  CoefOut_tmp(35) <= CoefData_35;
  CoefOut_tmp(36) <= CoefData_36;
  CoefOut_tmp(37) <= CoefData_37;
  CoefOut_tmp(38) <= CoefData_38;
  CoefOut_tmp(39) <= CoefData_39;
  CoefOut_tmp(40) <= CoefData_40;
  CoefOut_tmp(41) <= CoefData_41;
  CoefOut_tmp(42) <= CoefData_42;
  CoefOut_tmp(43) <= CoefData_43;
  CoefOut_tmp(44) <= CoefData_44;
  CoefOut_tmp(45) <= CoefData_45;
  CoefOut_tmp(46) <= CoefData_46;
  CoefOut_tmp(47) <= CoefData_47;
  CoefOut_tmp(48) <= CoefData_48;
  CoefOut_tmp(49) <= CoefData_49;
  CoefOut_tmp(50) <= CoefData_50;
  CoefOut_tmp(51) <= CoefData_51;
  CoefOut_tmp(52) <= CoefData_52;
  CoefOut_tmp(53) <= CoefData_53;
  CoefOut_tmp(54) <= CoefData_54;
  CoefOut_tmp(55) <= CoefData_55;
  CoefOut_tmp(56) <= CoefData_56;
  CoefOut_tmp(57) <= CoefData_57;
  CoefOut_tmp(58) <= CoefData_58;
  CoefOut_tmp(59) <= CoefData_59;
  CoefOut_tmp(60) <= CoefData_60;
  CoefOut_tmp(61) <= CoefData_61;
  CoefOut_tmp(62) <= CoefData_62;
  CoefOut_tmp(63) <= CoefData_63;
  CoefOut_tmp(64) <= CoefData_64;
  CoefOut_tmp(65) <= CoefData_65;
  CoefOut_tmp(66) <= CoefData_66;
  CoefOut_tmp(67) <= CoefData_67;
  CoefOut_tmp(68) <= CoefData_68;
  CoefOut_tmp(69) <= CoefData_69;
  CoefOut_tmp(70) <= CoefData_70;
  CoefOut_tmp(71) <= CoefData_71;
  CoefOut_tmp(72) <= CoefData_72;
  CoefOut_tmp(73) <= CoefData_73;
  CoefOut_tmp(74) <= CoefData_74;
  CoefOut_tmp(75) <= CoefData_75;
  CoefOut_tmp(76) <= CoefData_76;
  CoefOut_tmp(77) <= CoefData_77;
  CoefOut_tmp(78) <= CoefData_78;
  CoefOut_tmp(79) <= CoefData_79;

  outputgen: FOR k IN 0 TO 79 GENERATE
    CoefOut(k) <= std_logic_vector(CoefOut_tmp(k));
  END GENERATE;

END rtl;

