-- -------------------------------------------------------------
-- 
-- File Name: F:\Git_Repository\FPGA_myself\DDS\DDS_CSDN\DDS_32BIT\hdlsrc\NCO\NCO.vhd
-- Created: 2023-09-22 17:10:45
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.001
-- Target subsystem base rate: 0.001
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.001
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- NCO_VLD_OUT                   ce_out        0.001
-- WAVE_Out                      ce_out        0.001
-- FIR_VLD_OUT                   ce_out        0.001
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: NCO
-- Source Path: NCO
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY NCO IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        INC_IN                            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ce_out                            :   OUT   std_logic;
        NCO_VLD_OUT                       :   OUT   std_logic;
        WAVE_Out                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En13
        FIR_VLD_OUT                       :   OUT   std_logic
        );
END NCO;


ARCHITECTURE rtl OF NCO IS

  -- Component Declarations
  COMPONENT Subsystem
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          NCO_VLD_OUT                     :   OUT   std_logic;
          WAVE_Out                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En13
          FIR_VLD_OUT1                    :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem
    USE ENTITY work.Subsystem(rtl);

  -- Signals
  SIGNAL Subsystem_out1                   : std_logic;
  SIGNAL Subsystem_out2                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Subsystem_out3                   : std_logic;

BEGIN
  u_Subsystem : Subsystem
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              In1 => INC_IN,  -- uint32
              NCO_VLD_OUT => Subsystem_out1,
              WAVE_Out => Subsystem_out2,  -- sfix16_En13
              FIR_VLD_OUT1 => Subsystem_out3
              );

  ce_out <= clk_enable;

  NCO_VLD_OUT <= Subsystem_out1;

  WAVE_Out <= Subsystem_out2;

  FIR_VLD_OUT <= Subsystem_out3;

END rtl;

