-- -------------------------------------------------------------
-- 
-- File Name: F:\Git_Repository\FPGA_myself\DDS\DDS_CSDN\DDS_32BIT\hdlsrc\NCO\subFilter.vhd
-- Created: 2023-09-22 17:10:45
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: subFilter
-- Source Path: NCO/Subsystem/Discrete FIR Filter/Filter/subFilter
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.NCO_pkg.ALL;

ENTITY subFilter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        coefIn                            :   IN    vector_of_std_logic_vector16(0 TO 79);  -- sfix16_En17 [80]
        dinRegVld                         :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        dout_1_re                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En13
        doutVld                           :   OUT   std_logic
        );
END subFilter;


ARCHITECTURE rtl OF subFilter IS

  -- Component Declarations
  COMPONENT FilterTapSystolicPreAddWvlIn
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          dinPreAdd                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          coefIn_0                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En17
          addin                           :   IN    std_logic_vector(43 DOWNTO 0);  -- sfix44_En31
          dinRegVld                       :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          dinDly2                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          tapout                          :   OUT   std_logic_vector(43 DOWNTO 0)  -- sfix44_En31
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FilterTapSystolicPreAddWvlIn
    USE ENTITY work.FilterTapSystolicPreAddWvlIn(rtl);

  -- Signals
  SIGNAL intdelay_reg                     : std_logic_vector(0 TO 43);  -- ufix1 [44]
  SIGNAL vldShift                         : std_logic;
  SIGNAL vldOutTmp                        : std_logic;
  SIGNAL ZERO_OUT                         : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL addin                            : signed(43 DOWNTO 0);  -- sfix44_En31
  SIGNAL dinDly2                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL dinDly2_1                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout                           : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_2                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_1                         : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_3                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_2                         : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_4                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_3                         : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_5                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_4                         : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_6                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_5                         : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_7                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_6                         : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_8                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_7                         : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_9                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_8                         : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_10                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_9                         : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_11                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_10                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_12                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_11                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_13                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_12                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_14                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_13                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_15                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_14                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_16                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_15                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_17                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_16                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_18                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_17                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_19                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_18                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_20                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_19                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_21                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_20                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_22                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_21                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_23                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_22                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_24                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_23                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_25                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_24                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_26                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_25                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_27                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_26                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_28                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_27                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_29                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_28                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_30                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_29                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_31                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_30                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_32                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_31                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_33                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_32                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_34                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_33                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_35                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_34                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_36                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_35                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_37                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_36                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_38                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_37                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL dinDly2_39                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_38                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL tapout_39                        : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL tapout_signed                    : signed(43 DOWNTO 0);  -- sfix44_En31
  SIGNAL foutDly                          : signed(43 DOWNTO 0);  -- sfix44_En31
  SIGNAL dout_cast                        : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL muxOut                           : signed(15 DOWNTO 0);  -- sfix16_En13
  SIGNAL dout_1_re_tmp                    : signed(15 DOWNTO 0);  -- sfix16_En13

BEGIN
  u_FilterTap_1 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(0),  -- sfix16_En17
              addin => std_logic_vector(addin),  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_1,  -- sfix16_En14
              tapout => tapout  -- sfix44_En31
              );

  u_FilterTap_2 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_1,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(1),  -- sfix16_En17
              addin => tapout,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_2,  -- sfix16_En14
              tapout => tapout_1  -- sfix44_En31
              );

  u_FilterTap_3 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_2,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(2),  -- sfix16_En17
              addin => tapout_1,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_3,  -- sfix16_En14
              tapout => tapout_2  -- sfix44_En31
              );

  u_FilterTap_4 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_3,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(3),  -- sfix16_En17
              addin => tapout_2,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_4,  -- sfix16_En14
              tapout => tapout_3  -- sfix44_En31
              );

  u_FilterTap_5 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_4,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(4),  -- sfix16_En17
              addin => tapout_3,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_5,  -- sfix16_En14
              tapout => tapout_4  -- sfix44_En31
              );

  u_FilterTap_6 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_5,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(5),  -- sfix16_En17
              addin => tapout_4,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_6,  -- sfix16_En14
              tapout => tapout_5  -- sfix44_En31
              );

  u_FilterTap_7 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_6,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(6),  -- sfix16_En17
              addin => tapout_5,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_7,  -- sfix16_En14
              tapout => tapout_6  -- sfix44_En31
              );

  u_FilterTap_8 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_7,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(7),  -- sfix16_En17
              addin => tapout_6,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_8,  -- sfix16_En14
              tapout => tapout_7  -- sfix44_En31
              );

  u_FilterTap_9 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_8,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(8),  -- sfix16_En17
              addin => tapout_7,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_9,  -- sfix16_En14
              tapout => tapout_8  -- sfix44_En31
              );

  u_FilterTap_10 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_9,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(9),  -- sfix16_En17
              addin => tapout_8,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_10,  -- sfix16_En14
              tapout => tapout_9  -- sfix44_En31
              );

  u_FilterTap_11 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_10,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(10),  -- sfix16_En17
              addin => tapout_9,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_11,  -- sfix16_En14
              tapout => tapout_10  -- sfix44_En31
              );

  u_FilterTap_12 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_11,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(11),  -- sfix16_En17
              addin => tapout_10,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_12,  -- sfix16_En14
              tapout => tapout_11  -- sfix44_En31
              );

  u_FilterTap_13 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_12,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(12),  -- sfix16_En17
              addin => tapout_11,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_13,  -- sfix16_En14
              tapout => tapout_12  -- sfix44_En31
              );

  u_FilterTap_14 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_13,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(13),  -- sfix16_En17
              addin => tapout_12,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_14,  -- sfix16_En14
              tapout => tapout_13  -- sfix44_En31
              );

  u_FilterTap_15 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_14,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(14),  -- sfix16_En17
              addin => tapout_13,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_15,  -- sfix16_En14
              tapout => tapout_14  -- sfix44_En31
              );

  u_FilterTap_16 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_15,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(15),  -- sfix16_En17
              addin => tapout_14,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_16,  -- sfix16_En14
              tapout => tapout_15  -- sfix44_En31
              );

  u_FilterTap_17 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_16,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(16),  -- sfix16_En17
              addin => tapout_15,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_17,  -- sfix16_En14
              tapout => tapout_16  -- sfix44_En31
              );

  u_FilterTap_18 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_17,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(17),  -- sfix16_En17
              addin => tapout_16,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_18,  -- sfix16_En14
              tapout => tapout_17  -- sfix44_En31
              );

  u_FilterTap_19 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_18,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(18),  -- sfix16_En17
              addin => tapout_17,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_19,  -- sfix16_En14
              tapout => tapout_18  -- sfix44_En31
              );

  u_FilterTap_20 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_19,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(19),  -- sfix16_En17
              addin => tapout_18,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_20,  -- sfix16_En14
              tapout => tapout_19  -- sfix44_En31
              );

  u_FilterTap_21 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_20,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(20),  -- sfix16_En17
              addin => tapout_19,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_21,  -- sfix16_En14
              tapout => tapout_20  -- sfix44_En31
              );

  u_FilterTap_22 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_21,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(21),  -- sfix16_En17
              addin => tapout_20,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_22,  -- sfix16_En14
              tapout => tapout_21  -- sfix44_En31
              );

  u_FilterTap_23 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_22,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(22),  -- sfix16_En17
              addin => tapout_21,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_23,  -- sfix16_En14
              tapout => tapout_22  -- sfix44_En31
              );

  u_FilterTap_24 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_23,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(23),  -- sfix16_En17
              addin => tapout_22,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_24,  -- sfix16_En14
              tapout => tapout_23  -- sfix44_En31
              );

  u_FilterTap_25 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_24,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(24),  -- sfix16_En17
              addin => tapout_23,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_25,  -- sfix16_En14
              tapout => tapout_24  -- sfix44_En31
              );

  u_FilterTap_26 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_25,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(25),  -- sfix16_En17
              addin => tapout_24,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_26,  -- sfix16_En14
              tapout => tapout_25  -- sfix44_En31
              );

  u_FilterTap_27 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_26,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(26),  -- sfix16_En17
              addin => tapout_25,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_27,  -- sfix16_En14
              tapout => tapout_26  -- sfix44_En31
              );

  u_FilterTap_28 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_27,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(27),  -- sfix16_En17
              addin => tapout_26,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_28,  -- sfix16_En14
              tapout => tapout_27  -- sfix44_En31
              );

  u_FilterTap_29 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_28,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(28),  -- sfix16_En17
              addin => tapout_27,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_29,  -- sfix16_En14
              tapout => tapout_28  -- sfix44_En31
              );

  u_FilterTap_30 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_29,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(29),  -- sfix16_En17
              addin => tapout_28,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_30,  -- sfix16_En14
              tapout => tapout_29  -- sfix44_En31
              );

  u_FilterTap_31 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_30,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(30),  -- sfix16_En17
              addin => tapout_29,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_31,  -- sfix16_En14
              tapout => tapout_30  -- sfix44_En31
              );

  u_FilterTap_32 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_31,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(31),  -- sfix16_En17
              addin => tapout_30,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_32,  -- sfix16_En14
              tapout => tapout_31  -- sfix44_En31
              );

  u_FilterTap_33 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_32,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(32),  -- sfix16_En17
              addin => tapout_31,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_33,  -- sfix16_En14
              tapout => tapout_32  -- sfix44_En31
              );

  u_FilterTap_34 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_33,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(33),  -- sfix16_En17
              addin => tapout_32,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_34,  -- sfix16_En14
              tapout => tapout_33  -- sfix44_En31
              );

  u_FilterTap_35 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_34,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(34),  -- sfix16_En17
              addin => tapout_33,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_35,  -- sfix16_En14
              tapout => tapout_34  -- sfix44_En31
              );

  u_FilterTap_36 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_35,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(35),  -- sfix16_En17
              addin => tapout_34,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_36,  -- sfix16_En14
              tapout => tapout_35  -- sfix44_En31
              );

  u_FilterTap_37 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_36,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(36),  -- sfix16_En17
              addin => tapout_35,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_37,  -- sfix16_En14
              tapout => tapout_36  -- sfix44_En31
              );

  u_FilterTap_38 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_37,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(37),  -- sfix16_En17
              addin => tapout_36,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_38,  -- sfix16_En14
              tapout => tapout_37  -- sfix44_En31
              );

  u_FilterTap_39 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_38,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(38),  -- sfix16_En17
              addin => tapout_37,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_39,  -- sfix16_En14
              tapout => tapout_38  -- sfix44_En31
              );

  u_FilterTap_40 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_39,  -- sfix16_En14
              dinPreAdd => dinDly2,  -- sfix16_En14
              coefIn_0 => coefIn(39),  -- sfix16_En17
              addin => tapout_38,  -- sfix44_En31
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2,  -- sfix16_En14
              tapout => tapout_39  -- sfix44_En31
              );

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      intdelay_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          intdelay_reg <= (OTHERS => '0');
        ELSIF dinRegVld = '1' THEN
          intdelay_reg(0) <= dinRegVld;
          intdelay_reg(1 TO 43) <= intdelay_reg(0 TO 42);
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;

  vldShift <= intdelay_reg(43);

  vldOutTmp <= dinRegVld AND vldShift;

  ZERO_OUT <= to_signed(16#0000#, 16);

  addin <= to_signed(0, 44);

  tapout_signed <= signed(tapout_39);

  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      foutDly <= to_signed(0, 44);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          foutDly <= to_signed(0, 44);
        ELSIF dinRegVld = '1' THEN
          foutDly <= tapout_signed;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  dout_cast <= foutDly(33 DOWNTO 18);

  
  muxOut <= ZERO_OUT WHEN vldOutTmp = '0' ELSE
      dout_cast;

  intdelay_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dout_1_re_tmp <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          dout_1_re_tmp <= to_signed(16#0000#, 16);
        ELSE 
          dout_1_re_tmp <= muxOut;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


  dout_1_re <= std_logic_vector(dout_1_re_tmp);

  intdelay_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      doutVld <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF syncReset = '1' THEN
          doutVld <= '0';
        ELSE 
          doutVld <= vldOutTmp;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_3_process;


END rtl;

