vlib work
vlog  DECODER.v
vlog  alpha2BIT_SIPO.v
vlog  alpha2BIT_SIPO1.v
vlog  SIPO_4BIT.v
vlog  alpha2BIT_SIPO_block.v
vlog  alpha2BIT_SIPO1_block.v
vlog  SIPO_4BIT1.v
vlog  SIPO_8BIT.v
vlog  alpha2BIT_SIPO_block1.v
vlog  alpha2BIT_SIPO1_block1.v
vlog  SIPO_4BIT_block.v
vlog  alpha2BIT_SIPO_block2.v
vlog  alpha2BIT_SIPO1_block2.v
vlog  SIPO_4BIT1_block.v
vlog  SIPO_8BIT1.v
vlog  SIPO_16BIT.v
vlog  alpha2BIT_SIPO_block3.v
vlog  alpha2BIT_SIPO1_block3.v
vlog  SIPO_4BIT_block1.v
vlog  alpha2BIT_SIPO_block4.v
vlog  alpha2BIT_SIPO1_block4.v
vlog  SIPO_4BIT1_block1.v
vlog  SIPO_8BIT_block.v
vlog  alpha2BIT_SIPO_block5.v
vlog  alpha2BIT_SIPO1_block5.v
vlog  SIPO_4BIT_block2.v
vlog  alpha2BIT_SIPO_block6.v
vlog  alpha2BIT_SIPO1_block6.v
vlog  SIPO_4BIT1_block2.v
vlog  SIPO_8BIT1_block.v
vlog  SIPO_16BIT1.v
vlog  Subsystem.v
vlog  SIPO_32BIT_R.v
vlog  alpha2BIT_SIPO_block7.v
vlog  alpha2BIT_SIPO1_block7.v
vlog  SIPO_4BIT_block3.v
vlog  alpha2BIT_SIPO_block8.v
vlog  alpha2BIT_SIPO1_block8.v
vlog  SIPO_4BIT1_block3.v
vlog  SIPO_8BIT_block1.v
vlog  alpha2BIT_SIPO_block9.v
vlog  alpha2BIT_SIPO1_block9.v
vlog  SIPO_4BIT_block4.v
vlog  alpha2BIT_SIPO_block10.v
vlog  alpha2BIT_SIPO1_block10.v
vlog  SIPO_4BIT1_block4.v
vlog  SIPO_8BIT1_block1.v
vlog  SIPO_16BIT_block.v
vlog  alpha2BIT_SIPO_block11.v
vlog  alpha2BIT_SIPO1_block11.v
vlog  SIPO_4BIT_block5.v
vlog  alpha2BIT_SIPO_block12.v
vlog  alpha2BIT_SIPO1_block12.v
vlog  SIPO_4BIT1_block5.v
vlog  SIPO_8BIT_block2.v
vlog  alpha2BIT_SIPO_block13.v
vlog  alpha2BIT_SIPO1_block13.v
vlog  SIPO_4BIT_block6.v
vlog  alpha2BIT_SIPO_block14.v
vlog  alpha2BIT_SIPO1_block14.v
vlog  SIPO_4BIT1_block6.v
vlog  SIPO_8BIT1_block2.v
vlog  SIPO_16BIT1_block.v
vlog  Subsystem_block.v
vlog  SIPO_32BIT_R1.v
vlog  REC_I2S_NOFIFO.v
