// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\FPGA_myself\DDS\DDS_4\hdlsrc\NCO\FilterTapSystolicPreAddWvlIn.v
// Created: 2023-09-18 18:20:41
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterTapSystolicPreAddWvlIn
// Source Path: NCO/Subsystem/Discrete FIR Filter/Filter/subFilter/FilterTapSystolicPreAddWvlIn
// Hierarchy Level: 5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterTapSystolicPreAddWvlIn
          (clk,
           enb,
           dinReg2_0_re,
           dinPreAdd,
           coefIn_0,
           addin,
           dinRegVld,
           syncReset,
           dinDly2,
           tapout);


  input   clk;
  input   enb;
  input   signed [7:0] dinReg2_0_re;  // sfix8_En7
  input   signed [7:0] dinPreAdd;  // sfix8_En7
  input   signed [7:0] coefIn_0;  // sfix8_En8
  input   signed [43:0] addin;  // sfix44_En15
  input   dinRegVld;
  input   syncReset;
  output  signed [7:0] dinDly2;  // sfix8_En7
  output  signed [43:0] tapout;  // sfix44_En15


  reg signed [7:0] fTap_din1_reg1;  // sfix8
  reg signed [7:0] fTap_din1_reg2;  // sfix8
  reg signed [7:0] fTap_din1_reg3;  // sfix8
  reg signed [7:0] fTap_din2_reg1;  // sfix8
  reg signed [7:0] fTap_din2_reg2;  // sfix8
  reg signed [43:0] fTap_addout_reg;  // sfix44
  reg signed [7:0] fTap_coef_reg1;  // sfix8
  reg signed [7:0] fTap_coef_reg2;  // sfix8
  reg signed [7:0] fTap_din1_reg1_next;  // sfix8_En7
  reg signed [7:0] fTap_din1_reg2_next;  // sfix8_En7
  reg signed [7:0] fTap_din1_reg3_next;  // sfix8_En7
  reg signed [7:0] fTap_din2_reg1_next;  // sfix8_En7
  reg signed [7:0] fTap_din2_reg2_next;  // sfix8_En7
  reg signed [43:0] fTap_addout_reg_next;  // sfix44_En15
  reg signed [7:0] fTap_coef_reg1_next;  // sfix8_En8
  reg signed [7:0] fTap_coef_reg2_next;  // sfix8_En8
  reg signed [7:0] dinDly2_1;  // sfix8_En7
  reg signed [43:0] tapout_1;  // sfix44_En15
  reg signed [8:0] fTap_add_cast;  // sfix9_En7
  reg signed [8:0] fTap_add_cast_0;  // sfix9_En7
  reg signed [8:0] fTap_add_temp;  // sfix9_En7
  reg signed [16:0] fTap_mul_temp;  // sfix17_En15
  reg signed [43:0] fTap_add_cast_1;  // sfix44_En15

  initial begin
    fTap_din1_reg1 = 8'sb00000000;
    fTap_din1_reg2 = 8'sb00000000;
    fTap_din1_reg3 = 8'sb00000000;
    fTap_din2_reg1 = 8'sb00000000;
    fTap_din2_reg2 = 8'sb00000000;
    fTap_coef_reg1 = 8'sb00000000;
    fTap_coef_reg2 = 8'sb00000000;
    fTap_addout_reg = 44'sh00000000000;
  end

  // FilterTapSystolicPreAddWvldIn
  always @(posedge clk)
    begin : fTap_process
      if (enb) begin
        if (syncReset == 1'b1) begin
          fTap_din1_reg1 <= 8'sb00000000;
          fTap_din1_reg2 <= 8'sb00000000;
          fTap_din1_reg3 <= 8'sb00000000;
          fTap_din2_reg1 <= 8'sb00000000;
          fTap_din2_reg2 <= 8'sb00000000;
          fTap_coef_reg1 <= 8'sb00000000;
          fTap_coef_reg2 <= 8'sb00000000;
          fTap_addout_reg <= 44'sh00000000000;
        end
        else begin
          fTap_din1_reg1 <= fTap_din1_reg1_next;
          fTap_din1_reg2 <= fTap_din1_reg2_next;
          fTap_din1_reg3 <= fTap_din1_reg3_next;
          fTap_din2_reg1 <= fTap_din2_reg1_next;
          fTap_din2_reg2 <= fTap_din2_reg2_next;
          fTap_addout_reg <= fTap_addout_reg_next;
          fTap_coef_reg1 <= fTap_coef_reg1_next;
          fTap_coef_reg2 <= fTap_coef_reg2_next;
        end
      end
    end

  always @(addin, coefIn_0, dinPreAdd, dinReg2_0_re, dinRegVld, fTap_addout_reg,
       fTap_coef_reg1, fTap_coef_reg2, fTap_din1_reg1, fTap_din1_reg2,
       fTap_din1_reg3, fTap_din2_reg1, fTap_din2_reg2) begin
    fTap_add_temp = 9'sb000000000;
    fTap_mul_temp = 17'sb00000000000000000;
    fTap_add_cast = 9'sb000000000;
    fTap_add_cast_0 = 9'sb000000000;
    fTap_add_cast_1 = 44'sh00000000000;
    fTap_din1_reg1_next = fTap_din1_reg1;
    fTap_din1_reg2_next = fTap_din1_reg2;
    fTap_din1_reg3_next = fTap_din1_reg3;
    fTap_din2_reg1_next = fTap_din2_reg1;
    fTap_din2_reg2_next = fTap_din2_reg2;
    fTap_addout_reg_next = fTap_addout_reg;
    fTap_coef_reg1_next = fTap_coef_reg1;
    fTap_coef_reg2_next = fTap_coef_reg2;
    if (dinRegVld) begin
      fTap_add_cast = {fTap_din1_reg3[7], fTap_din1_reg3};
      fTap_add_cast_0 = {fTap_din2_reg2[7], fTap_din2_reg2};
      fTap_add_temp = fTap_add_cast + fTap_add_cast_0;
      fTap_mul_temp = fTap_add_temp * fTap_coef_reg2;
      fTap_add_cast_1 = {{27{fTap_mul_temp[16]}}, fTap_mul_temp};
      fTap_addout_reg_next = fTap_add_cast_1 + addin;
      fTap_din1_reg3_next = fTap_din1_reg2;
      fTap_din1_reg2_next = fTap_din1_reg1;
      fTap_din1_reg1_next = dinReg2_0_re;
      fTap_din2_reg2_next = fTap_din2_reg1;
      fTap_din2_reg1_next = dinPreAdd;
      fTap_coef_reg2_next = fTap_coef_reg1;
      fTap_coef_reg1_next = coefIn_0;
    end
    dinDly2_1 = fTap_din1_reg2;
    tapout_1 = fTap_addout_reg;
  end



  assign dinDly2 = dinDly2_1;

  assign tapout = tapout_1;

endmodule  // FilterTapSystolicPreAddWvlIn

