cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Demux','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Constant5','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay10','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay11','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay12','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay13','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay14','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay15','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay17','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay18','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay19','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay20','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay21','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay22','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay23','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay24','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay26','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay27','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay28','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay29','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay30','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay31','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay32','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay33','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay4','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay5','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay6','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay7','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay8','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/Delay9','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX1/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX1/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX1/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX1/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX10','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX10/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX10/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX10/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX10/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX11','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX11/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX11/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX11/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX11/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX12','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX12/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX12/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX12/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX12/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX13','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX13/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX13/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX13/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX13/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX14','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX14/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX14/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX14/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX14/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX15','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX15/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX15/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX15/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX15/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX16','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX16/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX16/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX16/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX16/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX17','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX17/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX17/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX17/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX17/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX18','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX18/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX18/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX18/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX18/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX19','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX19/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX19/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX19/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX19/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX2/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX2/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX2/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX2/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX20','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX20/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX20/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX20/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX20/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX21','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX21/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX21/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX21/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX21/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX22','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX22/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX22/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX22/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX22/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX23','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX23/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX23/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX23/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX23/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX24','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX24/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX24/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX24/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX24/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX25','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX25/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX25/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX25/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX25/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX26','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX26/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX26/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX26/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX26/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX27','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX27/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX27/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX27/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX27/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX28','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX28/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX28/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX28/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX28/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX29','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX29/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX29/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX29/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX29/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX3/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX3/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX3/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX3/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX30','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX30/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX30/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX30/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX30/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX31','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX31/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX31/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX31/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX31/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX4','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX4/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX4/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX4/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX4/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX5','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX5/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX5/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX5/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX5/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX6','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX6/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX6/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX6/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX6/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX7','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX7/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX7/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX7/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX7/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX8','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX8/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX8/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX8/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX8/Logical Operator3','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX9','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX9/Logical Operator','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX9/Logical Operator1','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX9/Logical Operator2','user1');
hilite_system('I2S/I2S/PISO_SHIFT_REG_RIGHT1/Subsystem/MUX9/Logical Operator3','user1');
