vlib work
vlog  MUX15.v
vlog  MUX.v
vlog  MUX1.v
vlog  MUX10.v
vlog  MUX11.v
vlog  MUX12.v
vlog  MUX13.v
vlog  MUX14.v
vlog  MUX15_block.v
vlog  MUX16.v
vlog  MUX17.v
vlog  MUX18.v
vlog  MUX19.v
vlog  MUX2.v
vlog  MUX20.v
vlog  MUX21.v
vlog  MUX22.v
vlog  MUX23.v
vlog  MUX24.v
vlog  MUX25.v
vlog  MUX26.v
vlog  MUX27.v
vlog  MUX28.v
vlog  MUX29.v
vlog  MUX3.v
vlog  MUX30.v
vlog  MUX31.v
vlog  MUX4.v
vlog  MUX5.v
vlog  MUX6.v
vlog  MUX7.v
vlog  MUX8.v
vlog  MUX9.v
vlog  Subsystem.v
vlog  PISO_SHIFT_REG_LEFT.v
vlog  MUX_block.v
vlog  MUX1_block.v
vlog  MUX10_block.v
vlog  MUX11_block.v
vlog  MUX12_block.v
vlog  MUX13_block.v
vlog  MUX14_block.v
vlog  MUX15_block1.v
vlog  MUX16_block.v
vlog  MUX17_block.v
vlog  MUX18_block.v
vlog  MUX19_block.v
vlog  MUX2_block.v
vlog  MUX20_block.v
vlog  MUX21_block.v
vlog  MUX22_block.v
vlog  MUX23_block.v
vlog  MUX24_block.v
vlog  MUX25_block.v
vlog  MUX26_block.v
vlog  MUX27_block.v
vlog  MUX28_block.v
vlog  MUX29_block.v
vlog  MUX3_block.v
vlog  MUX30_block.v
vlog  MUX31_block.v
vlog  MUX4_block.v
vlog  MUX5_block.v
vlog  MUX6_block.v
vlog  MUX7_block.v
vlog  MUX8_block.v
vlog  MUX9_block.v
vlog  Subsystem_block.v
vlog  PISO_SHIFT_REG_RIGHT.v
vlog  I2S.v
vlog  I2S_tb.v
