// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\DDS\DDS.v
// Created: 2023-09-20 16:09:04
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 2e-08
// Target subsystem base rate: 2e-08
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        2e-08
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// FIR_OUT                       ce_out        2e-08
// NCO_VLD                       ce_out        2e-08
// FIR_VLD                       ce_out        2e-08
// NCO_OUT                       ce_out        2e-08
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DDS
// Source Path: DDS
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DDS
          (clk,
           reset,
           clk_enable,
           INC,
           ce_out,
           FIR_OUT,
           NCO_VLD,
           FIR_VLD,
           NCO_OUT);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [15:0] INC;  // uint16
  output  ce_out;
  output  signed [15:0] FIR_OUT;  // sfix16_En13
  output  NCO_VLD;
  output  FIR_VLD;
  output  signed [15:0] NCO_OUT;  // sfix16_En14


  wire signed [15:0] Subsystem_out1;  // sfix16_En13
  wire Subsystem_out2;
  wire Subsystem_out3;
  wire signed [15:0] Subsystem_out4;  // sfix16_En14


  Subsystem u_Subsystem (.clk(clk),
                         .reset(reset),
                         .enb(clk_enable),
                         .INC(INC),  // uint16
                         .FIR_OUT(Subsystem_out1),  // sfix16_En13
                         .NCO_VLD(Subsystem_out2),
                         .FIR_VLD(Subsystem_out3),
                         .NCO_OUT(Subsystem_out4)  // sfix16_En14
                         );

  assign FIR_OUT = Subsystem_out1;

  assign NCO_VLD = Subsystem_out2;

  assign FIR_VLD = Subsystem_out3;

  assign NCO_OUT = Subsystem_out4;

  assign ce_out = clk_enable;

endmodule  // DDS

