// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\rec_i2s\alpha2BIT_SIPO_block5.v
// Created: 2023-10-27 19:54:39
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: alpha2BIT_SIPO_block5
// Source Path: rec_i2s/REC_I2S/SIPO_16BIT_R/SIPO_8BIT1/SIPO_4BIT/2BIT_SIPO
// Hierarchy Level: 5
// Model version: 1.35
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module alpha2BIT_SIPO_block5
          (clk,
           reset,
           enb,
           SERIAL_IN,
           PARA_OUT_0,
           PARA_OUT_1,
           SERIAL_OUT);


  input   clk;
  input   reset;
  input   enb;
  input   SERIAL_IN;
  output  PARA_OUT_0;  // boolean
  output  PARA_OUT_1;  // boolean
  output  SERIAL_OUT;


  wire Constant_out1;
  reg  Delay_bypass_delay;  // ufix1
  reg  Delay_reg;  // ufix1
  wire Delay_out1;
  reg  Delay1_bypass_delay;  // ufix1
  reg  Delay1_reg;  // ufix1
  wire Delay1_out1;


  assign Constant_out1 = 1'b1;



  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_bypass_delay <= 1'b0;
        Delay_reg <= 1'b0;
      end
      else begin
        if (enb && Constant_out1) begin
          Delay_bypass_delay <= Delay_reg;
          Delay_reg <= SERIAL_IN;
        end
      end
    end

  assign Delay_out1 = (Constant_out1 == 1'b1 ? Delay_reg :
              Delay_bypass_delay);



  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_bypass_delay <= 1'b0;
        Delay1_reg <= 1'b0;
      end
      else begin
        if (enb && Constant_out1) begin
          Delay1_bypass_delay <= Delay1_reg;
          Delay1_reg <= Delay_out1;
        end
      end
    end

  assign Delay1_out1 = (Constant_out1 == 1'b1 ? Delay1_reg :
              Delay1_bypass_delay);



  assign PARA_OUT_0 = Delay1_out1;

  assign PARA_OUT_1 = Delay_out1;

  assign SERIAL_OUT = Delay1_out1;

endmodule  // alpha2BIT_SIPO_block5

