// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\rec_i2s\REC_I2S_NOFIFO.v
// Created: 2023-10-28 15:45:10
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// PARA_OUT_L_0                  ce_out        1
// PARA_OUT_L_1                  ce_out        1
// PARA_OUT_L_2                  ce_out        1
// PARA_OUT_L_3                  ce_out        1
// PARA_OUT_L_4                  ce_out        1
// PARA_OUT_L_5                  ce_out        1
// PARA_OUT_L_6                  ce_out        1
// PARA_OUT_L_7                  ce_out        1
// PARA_OUT_L_8                  ce_out        1
// PARA_OUT_L_9                  ce_out        1
// PARA_OUT_L_10                 ce_out        1
// PARA_OUT_L_11                 ce_out        1
// PARA_OUT_L_12                 ce_out        1
// PARA_OUT_L_13                 ce_out        1
// PARA_OUT_L_14                 ce_out        1
// PARA_OUT_L_15                 ce_out        1
// PARA_OUT_L_16                 ce_out        1
// PARA_OUT_L_17                 ce_out        1
// PARA_OUT_L_18                 ce_out        1
// PARA_OUT_L_19                 ce_out        1
// PARA_OUT_L_20                 ce_out        1
// PARA_OUT_L_21                 ce_out        1
// PARA_OUT_L_22                 ce_out        1
// PARA_OUT_L_23                 ce_out        1
// PARA_OUT_L_24                 ce_out        1
// PARA_OUT_L_25                 ce_out        1
// PARA_OUT_L_26                 ce_out        1
// PARA_OUT_L_27                 ce_out        1
// PARA_OUT_L_28                 ce_out        1
// PARA_OUT_L_29                 ce_out        1
// PARA_OUT_L_30                 ce_out        1
// PARA_OUT_L_31                 ce_out        1
// PARA_OUT_R_0                  ce_out        1
// PARA_OUT_R_1                  ce_out        1
// PARA_OUT_R_2                  ce_out        1
// PARA_OUT_R_3                  ce_out        1
// PARA_OUT_R_4                  ce_out        1
// PARA_OUT_R_5                  ce_out        1
// PARA_OUT_R_6                  ce_out        1
// PARA_OUT_R_7                  ce_out        1
// PARA_OUT_R_8                  ce_out        1
// PARA_OUT_R_9                  ce_out        1
// PARA_OUT_R_10                 ce_out        1
// PARA_OUT_R_11                 ce_out        1
// PARA_OUT_R_12                 ce_out        1
// PARA_OUT_R_13                 ce_out        1
// PARA_OUT_R_14                 ce_out        1
// PARA_OUT_R_15                 ce_out        1
// PARA_OUT_R_16                 ce_out        1
// PARA_OUT_R_17                 ce_out        1
// PARA_OUT_R_18                 ce_out        1
// PARA_OUT_R_19                 ce_out        1
// PARA_OUT_R_20                 ce_out        1
// PARA_OUT_R_21                 ce_out        1
// PARA_OUT_R_22                 ce_out        1
// PARA_OUT_R_23                 ce_out        1
// PARA_OUT_R_24                 ce_out        1
// PARA_OUT_R_25                 ce_out        1
// PARA_OUT_R_26                 ce_out        1
// PARA_OUT_R_27                 ce_out        1
// PARA_OUT_R_28                 ce_out        1
// PARA_OUT_R_29                 ce_out        1
// PARA_OUT_R_30                 ce_out        1
// PARA_OUT_R_31                 ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: REC_I2S_NOFIFO
// Source Path: rec_i2s/REC_I2S_NOFIFO
// Hierarchy Level: 0
// Model version: 1.42
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module REC_I2S_NOFIFO
          (clk,
           reset,
           clk_enable,
           LRCLK_IN,
           SDATA_IN,
           SCLK_IN,
           ce_out,
           PARA_OUT_L_0,
           PARA_OUT_L_1,
           PARA_OUT_L_2,
           PARA_OUT_L_3,
           PARA_OUT_L_4,
           PARA_OUT_L_5,
           PARA_OUT_L_6,
           PARA_OUT_L_7,
           PARA_OUT_L_8,
           PARA_OUT_L_9,
           PARA_OUT_L_10,
           PARA_OUT_L_11,
           PARA_OUT_L_12,
           PARA_OUT_L_13,
           PARA_OUT_L_14,
           PARA_OUT_L_15,
           PARA_OUT_L_16,
           PARA_OUT_L_17,
           PARA_OUT_L_18,
           PARA_OUT_L_19,
           PARA_OUT_L_20,
           PARA_OUT_L_21,
           PARA_OUT_L_22,
           PARA_OUT_L_23,
           PARA_OUT_L_24,
           PARA_OUT_L_25,
           PARA_OUT_L_26,
           PARA_OUT_L_27,
           PARA_OUT_L_28,
           PARA_OUT_L_29,
           PARA_OUT_L_30,
           PARA_OUT_L_31,
           PARA_OUT_R_0,
           PARA_OUT_R_1,
           PARA_OUT_R_2,
           PARA_OUT_R_3,
           PARA_OUT_R_4,
           PARA_OUT_R_5,
           PARA_OUT_R_6,
           PARA_OUT_R_7,
           PARA_OUT_R_8,
           PARA_OUT_R_9,
           PARA_OUT_R_10,
           PARA_OUT_R_11,
           PARA_OUT_R_12,
           PARA_OUT_R_13,
           PARA_OUT_R_14,
           PARA_OUT_R_15,
           PARA_OUT_R_16,
           PARA_OUT_R_17,
           PARA_OUT_R_18,
           PARA_OUT_R_19,
           PARA_OUT_R_20,
           PARA_OUT_R_21,
           PARA_OUT_R_22,
           PARA_OUT_R_23,
           PARA_OUT_R_24,
           PARA_OUT_R_25,
           PARA_OUT_R_26,
           PARA_OUT_R_27,
           PARA_OUT_R_28,
           PARA_OUT_R_29,
           PARA_OUT_R_30,
           PARA_OUT_R_31);


  input   clk;
  input   reset;
  input   clk_enable;
  input   LRCLK_IN;
  input   SDATA_IN;
  input   SCLK_IN;
  output  ce_out;
  output  PARA_OUT_L_0;  // boolean
  output  PARA_OUT_L_1;  // boolean
  output  PARA_OUT_L_2;  // boolean
  output  PARA_OUT_L_3;  // boolean
  output  PARA_OUT_L_4;  // boolean
  output  PARA_OUT_L_5;  // boolean
  output  PARA_OUT_L_6;  // boolean
  output  PARA_OUT_L_7;  // boolean
  output  PARA_OUT_L_8;  // boolean
  output  PARA_OUT_L_9;  // boolean
  output  PARA_OUT_L_10;  // boolean
  output  PARA_OUT_L_11;  // boolean
  output  PARA_OUT_L_12;  // boolean
  output  PARA_OUT_L_13;  // boolean
  output  PARA_OUT_L_14;  // boolean
  output  PARA_OUT_L_15;  // boolean
  output  PARA_OUT_L_16;  // boolean
  output  PARA_OUT_L_17;  // boolean
  output  PARA_OUT_L_18;  // boolean
  output  PARA_OUT_L_19;  // boolean
  output  PARA_OUT_L_20;  // boolean
  output  PARA_OUT_L_21;  // boolean
  output  PARA_OUT_L_22;  // boolean
  output  PARA_OUT_L_23;  // boolean
  output  PARA_OUT_L_24;  // boolean
  output  PARA_OUT_L_25;  // boolean
  output  PARA_OUT_L_26;  // boolean
  output  PARA_OUT_L_27;  // boolean
  output  PARA_OUT_L_28;  // boolean
  output  PARA_OUT_L_29;  // boolean
  output  PARA_OUT_L_30;  // boolean
  output  PARA_OUT_L_31;  // boolean
  output  PARA_OUT_R_0;  // boolean
  output  PARA_OUT_R_1;  // boolean
  output  PARA_OUT_R_2;  // boolean
  output  PARA_OUT_R_3;  // boolean
  output  PARA_OUT_R_4;  // boolean
  output  PARA_OUT_R_5;  // boolean
  output  PARA_OUT_R_6;  // boolean
  output  PARA_OUT_R_7;  // boolean
  output  PARA_OUT_R_8;  // boolean
  output  PARA_OUT_R_9;  // boolean
  output  PARA_OUT_R_10;  // boolean
  output  PARA_OUT_R_11;  // boolean
  output  PARA_OUT_R_12;  // boolean
  output  PARA_OUT_R_13;  // boolean
  output  PARA_OUT_R_14;  // boolean
  output  PARA_OUT_R_15;  // boolean
  output  PARA_OUT_R_16;  // boolean
  output  PARA_OUT_R_17;  // boolean
  output  PARA_OUT_R_18;  // boolean
  output  PARA_OUT_R_19;  // boolean
  output  PARA_OUT_R_20;  // boolean
  output  PARA_OUT_R_21;  // boolean
  output  PARA_OUT_R_22;  // boolean
  output  PARA_OUT_R_23;  // boolean
  output  PARA_OUT_R_24;  // boolean
  output  PARA_OUT_R_25;  // boolean
  output  PARA_OUT_R_26;  // boolean
  output  PARA_OUT_R_27;  // boolean
  output  PARA_OUT_R_28;  // boolean
  output  PARA_OUT_R_29;  // boolean
  output  PARA_OUT_R_30;  // boolean
  output  PARA_OUT_R_31;  // boolean


  wire enb;
  reg  Delay_bypass_delay;  // ufix1
  reg  Delay_reg;  // ufix1
  wire Delay_out1;
  wire DECODER_out1;
  wire DECODER_out2;
  wire SIPO_32BIT_R1_out1_0;
  wire SIPO_32BIT_R1_out1_1;
  wire SIPO_32BIT_R1_out1_2;
  wire SIPO_32BIT_R1_out1_3;
  wire SIPO_32BIT_R1_out1_4;
  wire SIPO_32BIT_R1_out1_5;
  wire SIPO_32BIT_R1_out1_6;
  wire SIPO_32BIT_R1_out1_7;
  wire SIPO_32BIT_R1_out1_8;
  wire SIPO_32BIT_R1_out1_9;
  wire SIPO_32BIT_R1_out1_10;
  wire SIPO_32BIT_R1_out1_11;
  wire SIPO_32BIT_R1_out1_12;
  wire SIPO_32BIT_R1_out1_13;
  wire SIPO_32BIT_R1_out1_14;
  wire SIPO_32BIT_R1_out1_15;
  wire SIPO_32BIT_R1_out1_16;
  wire SIPO_32BIT_R1_out1_17;
  wire SIPO_32BIT_R1_out1_18;
  wire SIPO_32BIT_R1_out1_19;
  wire SIPO_32BIT_R1_out1_20;
  wire SIPO_32BIT_R1_out1_21;
  wire SIPO_32BIT_R1_out1_22;
  wire SIPO_32BIT_R1_out1_23;
  wire SIPO_32BIT_R1_out1_24;
  wire SIPO_32BIT_R1_out1_25;
  wire SIPO_32BIT_R1_out1_26;
  wire SIPO_32BIT_R1_out1_27;
  wire SIPO_32BIT_R1_out1_28;
  wire SIPO_32BIT_R1_out1_29;
  wire SIPO_32BIT_R1_out1_30;
  wire SIPO_32BIT_R1_out1_31;
  wire SIPO_32BIT_R_out1_0;
  wire SIPO_32BIT_R_out1_1;
  wire SIPO_32BIT_R_out1_2;
  wire SIPO_32BIT_R_out1_3;
  wire SIPO_32BIT_R_out1_4;
  wire SIPO_32BIT_R_out1_5;
  wire SIPO_32BIT_R_out1_6;
  wire SIPO_32BIT_R_out1_7;
  wire SIPO_32BIT_R_out1_8;
  wire SIPO_32BIT_R_out1_9;
  wire SIPO_32BIT_R_out1_10;
  wire SIPO_32BIT_R_out1_11;
  wire SIPO_32BIT_R_out1_12;
  wire SIPO_32BIT_R_out1_13;
  wire SIPO_32BIT_R_out1_14;
  wire SIPO_32BIT_R_out1_15;
  wire SIPO_32BIT_R_out1_16;
  wire SIPO_32BIT_R_out1_17;
  wire SIPO_32BIT_R_out1_18;
  wire SIPO_32BIT_R_out1_19;
  wire SIPO_32BIT_R_out1_20;
  wire SIPO_32BIT_R_out1_21;
  wire SIPO_32BIT_R_out1_22;
  wire SIPO_32BIT_R_out1_23;
  wire SIPO_32BIT_R_out1_24;
  wire SIPO_32BIT_R_out1_25;
  wire SIPO_32BIT_R_out1_26;
  wire SIPO_32BIT_R_out1_27;
  wire SIPO_32BIT_R_out1_28;
  wire SIPO_32BIT_R_out1_29;
  wire SIPO_32BIT_R_out1_30;
  wire SIPO_32BIT_R_out1_31;

  // LRCLK为低电平时左声道输出，加载右声道数据


  assign enb = clk_enable;

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_bypass_delay <= 1'b0;
        Delay_reg <= 1'b0;
      end
      else begin
        if (enb && SCLK_IN) begin
          Delay_bypass_delay <= Delay_reg;
          Delay_reg <= SDATA_IN;
        end
      end
    end

  assign Delay_out1 = (SCLK_IN == 1'b1 ? Delay_reg :
              Delay_bypass_delay);



  DECODER u_DECODER (.IN_L(Delay_out1),
                     .SEL(LRCLK_IN),
                     .L_OUT(DECODER_out1),
                     .R_OUT(DECODER_out2)
                     );

  SIPO_32BIT_R1 u_SIPO_32BIT_R1 (.clk(clk),
                                 .reset(reset),
                                 .enb(clk_enable),
                                 .SERIAL_IN(DECODER_out1),
                                 .PARA_OUT_0(SIPO_32BIT_R1_out1_0),  // boolean
                                 .PARA_OUT_1(SIPO_32BIT_R1_out1_1),  // boolean
                                 .PARA_OUT_2(SIPO_32BIT_R1_out1_2),  // boolean
                                 .PARA_OUT_3(SIPO_32BIT_R1_out1_3),  // boolean
                                 .PARA_OUT_4(SIPO_32BIT_R1_out1_4),  // boolean
                                 .PARA_OUT_5(SIPO_32BIT_R1_out1_5),  // boolean
                                 .PARA_OUT_6(SIPO_32BIT_R1_out1_6),  // boolean
                                 .PARA_OUT_7(SIPO_32BIT_R1_out1_7),  // boolean
                                 .PARA_OUT_8(SIPO_32BIT_R1_out1_8),  // boolean
                                 .PARA_OUT_9(SIPO_32BIT_R1_out1_9),  // boolean
                                 .PARA_OUT_10(SIPO_32BIT_R1_out1_10),  // boolean
                                 .PARA_OUT_11(SIPO_32BIT_R1_out1_11),  // boolean
                                 .PARA_OUT_12(SIPO_32BIT_R1_out1_12),  // boolean
                                 .PARA_OUT_13(SIPO_32BIT_R1_out1_13),  // boolean
                                 .PARA_OUT_14(SIPO_32BIT_R1_out1_14),  // boolean
                                 .PARA_OUT_15(SIPO_32BIT_R1_out1_15),  // boolean
                                 .PARA_OUT_16(SIPO_32BIT_R1_out1_16),  // boolean
                                 .PARA_OUT_17(SIPO_32BIT_R1_out1_17),  // boolean
                                 .PARA_OUT_18(SIPO_32BIT_R1_out1_18),  // boolean
                                 .PARA_OUT_19(SIPO_32BIT_R1_out1_19),  // boolean
                                 .PARA_OUT_20(SIPO_32BIT_R1_out1_20),  // boolean
                                 .PARA_OUT_21(SIPO_32BIT_R1_out1_21),  // boolean
                                 .PARA_OUT_22(SIPO_32BIT_R1_out1_22),  // boolean
                                 .PARA_OUT_23(SIPO_32BIT_R1_out1_23),  // boolean
                                 .PARA_OUT_24(SIPO_32BIT_R1_out1_24),  // boolean
                                 .PARA_OUT_25(SIPO_32BIT_R1_out1_25),  // boolean
                                 .PARA_OUT_26(SIPO_32BIT_R1_out1_26),  // boolean
                                 .PARA_OUT_27(SIPO_32BIT_R1_out1_27),  // boolean
                                 .PARA_OUT_28(SIPO_32BIT_R1_out1_28),  // boolean
                                 .PARA_OUT_29(SIPO_32BIT_R1_out1_29),  // boolean
                                 .PARA_OUT_30(SIPO_32BIT_R1_out1_30),  // boolean
                                 .PARA_OUT_31(SIPO_32BIT_R1_out1_31)  // boolean
                                 );

  assign PARA_OUT_L_0 = SIPO_32BIT_R1_out1_0;

  assign PARA_OUT_L_1 = SIPO_32BIT_R1_out1_1;

  assign PARA_OUT_L_2 = SIPO_32BIT_R1_out1_2;

  assign PARA_OUT_L_3 = SIPO_32BIT_R1_out1_3;

  assign PARA_OUT_L_4 = SIPO_32BIT_R1_out1_4;

  assign PARA_OUT_L_5 = SIPO_32BIT_R1_out1_5;

  assign PARA_OUT_L_6 = SIPO_32BIT_R1_out1_6;

  assign PARA_OUT_L_7 = SIPO_32BIT_R1_out1_7;

  assign PARA_OUT_L_8 = SIPO_32BIT_R1_out1_8;

  assign PARA_OUT_L_9 = SIPO_32BIT_R1_out1_9;

  assign PARA_OUT_L_10 = SIPO_32BIT_R1_out1_10;

  assign PARA_OUT_L_11 = SIPO_32BIT_R1_out1_11;

  assign PARA_OUT_L_12 = SIPO_32BIT_R1_out1_12;

  assign PARA_OUT_L_13 = SIPO_32BIT_R1_out1_13;

  assign PARA_OUT_L_14 = SIPO_32BIT_R1_out1_14;

  assign PARA_OUT_L_15 = SIPO_32BIT_R1_out1_15;

  assign PARA_OUT_L_16 = SIPO_32BIT_R1_out1_16;

  assign PARA_OUT_L_17 = SIPO_32BIT_R1_out1_17;

  assign PARA_OUT_L_18 = SIPO_32BIT_R1_out1_18;

  assign PARA_OUT_L_19 = SIPO_32BIT_R1_out1_19;

  assign PARA_OUT_L_20 = SIPO_32BIT_R1_out1_20;

  assign PARA_OUT_L_21 = SIPO_32BIT_R1_out1_21;

  assign PARA_OUT_L_22 = SIPO_32BIT_R1_out1_22;

  assign PARA_OUT_L_23 = SIPO_32BIT_R1_out1_23;

  assign PARA_OUT_L_24 = SIPO_32BIT_R1_out1_24;

  assign PARA_OUT_L_25 = SIPO_32BIT_R1_out1_25;

  assign PARA_OUT_L_26 = SIPO_32BIT_R1_out1_26;

  assign PARA_OUT_L_27 = SIPO_32BIT_R1_out1_27;

  assign PARA_OUT_L_28 = SIPO_32BIT_R1_out1_28;

  assign PARA_OUT_L_29 = SIPO_32BIT_R1_out1_29;

  assign PARA_OUT_L_30 = SIPO_32BIT_R1_out1_30;

  assign PARA_OUT_L_31 = SIPO_32BIT_R1_out1_31;

  SIPO_32BIT_R u_SIPO_32BIT_R (.clk(clk),
                               .reset(reset),
                               .enb(clk_enable),
                               .SERIAL_IN(DECODER_out2),
                               .PARA_OUT_0(SIPO_32BIT_R_out1_0),  // boolean
                               .PARA_OUT_1(SIPO_32BIT_R_out1_1),  // boolean
                               .PARA_OUT_2(SIPO_32BIT_R_out1_2),  // boolean
                               .PARA_OUT_3(SIPO_32BIT_R_out1_3),  // boolean
                               .PARA_OUT_4(SIPO_32BIT_R_out1_4),  // boolean
                               .PARA_OUT_5(SIPO_32BIT_R_out1_5),  // boolean
                               .PARA_OUT_6(SIPO_32BIT_R_out1_6),  // boolean
                               .PARA_OUT_7(SIPO_32BIT_R_out1_7),  // boolean
                               .PARA_OUT_8(SIPO_32BIT_R_out1_8),  // boolean
                               .PARA_OUT_9(SIPO_32BIT_R_out1_9),  // boolean
                               .PARA_OUT_10(SIPO_32BIT_R_out1_10),  // boolean
                               .PARA_OUT_11(SIPO_32BIT_R_out1_11),  // boolean
                               .PARA_OUT_12(SIPO_32BIT_R_out1_12),  // boolean
                               .PARA_OUT_13(SIPO_32BIT_R_out1_13),  // boolean
                               .PARA_OUT_14(SIPO_32BIT_R_out1_14),  // boolean
                               .PARA_OUT_15(SIPO_32BIT_R_out1_15),  // boolean
                               .PARA_OUT_16(SIPO_32BIT_R_out1_16),  // boolean
                               .PARA_OUT_17(SIPO_32BIT_R_out1_17),  // boolean
                               .PARA_OUT_18(SIPO_32BIT_R_out1_18),  // boolean
                               .PARA_OUT_19(SIPO_32BIT_R_out1_19),  // boolean
                               .PARA_OUT_20(SIPO_32BIT_R_out1_20),  // boolean
                               .PARA_OUT_21(SIPO_32BIT_R_out1_21),  // boolean
                               .PARA_OUT_22(SIPO_32BIT_R_out1_22),  // boolean
                               .PARA_OUT_23(SIPO_32BIT_R_out1_23),  // boolean
                               .PARA_OUT_24(SIPO_32BIT_R_out1_24),  // boolean
                               .PARA_OUT_25(SIPO_32BIT_R_out1_25),  // boolean
                               .PARA_OUT_26(SIPO_32BIT_R_out1_26),  // boolean
                               .PARA_OUT_27(SIPO_32BIT_R_out1_27),  // boolean
                               .PARA_OUT_28(SIPO_32BIT_R_out1_28),  // boolean
                               .PARA_OUT_29(SIPO_32BIT_R_out1_29),  // boolean
                               .PARA_OUT_30(SIPO_32BIT_R_out1_30),  // boolean
                               .PARA_OUT_31(SIPO_32BIT_R_out1_31)  // boolean
                               );

  assign PARA_OUT_R_0 = SIPO_32BIT_R_out1_0;

  assign PARA_OUT_R_1 = SIPO_32BIT_R_out1_1;

  assign PARA_OUT_R_2 = SIPO_32BIT_R_out1_2;

  assign PARA_OUT_R_3 = SIPO_32BIT_R_out1_3;

  assign PARA_OUT_R_4 = SIPO_32BIT_R_out1_4;

  assign PARA_OUT_R_5 = SIPO_32BIT_R_out1_5;

  assign PARA_OUT_R_6 = SIPO_32BIT_R_out1_6;

  assign PARA_OUT_R_7 = SIPO_32BIT_R_out1_7;

  assign PARA_OUT_R_8 = SIPO_32BIT_R_out1_8;

  assign PARA_OUT_R_9 = SIPO_32BIT_R_out1_9;

  assign PARA_OUT_R_10 = SIPO_32BIT_R_out1_10;

  assign PARA_OUT_R_11 = SIPO_32BIT_R_out1_11;

  assign PARA_OUT_R_12 = SIPO_32BIT_R_out1_12;

  assign PARA_OUT_R_13 = SIPO_32BIT_R_out1_13;

  assign PARA_OUT_R_14 = SIPO_32BIT_R_out1_14;

  assign PARA_OUT_R_15 = SIPO_32BIT_R_out1_15;

  assign PARA_OUT_R_16 = SIPO_32BIT_R_out1_16;

  assign PARA_OUT_R_17 = SIPO_32BIT_R_out1_17;

  assign PARA_OUT_R_18 = SIPO_32BIT_R_out1_18;

  assign PARA_OUT_R_19 = SIPO_32BIT_R_out1_19;

  assign PARA_OUT_R_20 = SIPO_32BIT_R_out1_20;

  assign PARA_OUT_R_21 = SIPO_32BIT_R_out1_21;

  assign PARA_OUT_R_22 = SIPO_32BIT_R_out1_22;

  assign PARA_OUT_R_23 = SIPO_32BIT_R_out1_23;

  assign PARA_OUT_R_24 = SIPO_32BIT_R_out1_24;

  assign PARA_OUT_R_25 = SIPO_32BIT_R_out1_25;

  assign PARA_OUT_R_26 = SIPO_32BIT_R_out1_26;

  assign PARA_OUT_R_27 = SIPO_32BIT_R_out1_27;

  assign PARA_OUT_R_28 = SIPO_32BIT_R_out1_28;

  assign PARA_OUT_R_29 = SIPO_32BIT_R_out1_29;

  assign PARA_OUT_R_30 = SIPO_32BIT_R_out1_30;

  assign PARA_OUT_R_31 = SIPO_32BIT_R_out1_31;

  assign ce_out = clk_enable;

endmodule  // REC_I2S_NOFIFO

