vlib work
vlog  alpha2BIT_SIPO.v
vlog  alpha2BIT_SIPO1.v
vlog  SIPO_4BIT.v
vlog  alpha2BIT_SIPO_block.v
vlog  alpha2BIT_SIPO1_block.v
vlog  SIPO_4BIT1.v
vlog  SIPO_8BIT.v
vlog  alpha2BIT_SIPO_block1.v
vlog  alpha2BIT_SIPO1_block1.v
vlog  SIPO_4BIT_block.v
vlog  alpha2BIT_SIPO_block2.v
vlog  alpha2BIT_SIPO1_block2.v
vlog  SIPO_4BIT1_block.v
vlog  SIPO_8BIT1.v
vlog  SIPO_16BIT_L.v
vlog  alpha2BIT_SIPO_block3.v
vlog  alpha2BIT_SIPO1_block3.v
vlog  SIPO_4BIT_block1.v
vlog  alpha2BIT_SIPO_block4.v
vlog  alpha2BIT_SIPO1_block4.v
vlog  SIPO_4BIT1_block1.v
vlog  SIPO_8BIT_block.v
vlog  alpha2BIT_SIPO_block5.v
vlog  alpha2BIT_SIPO1_block5.v
vlog  SIPO_4BIT_block2.v
vlog  alpha2BIT_SIPO_block6.v
vlog  alpha2BIT_SIPO1_block6.v
vlog  SIPO_4BIT1_block2.v
vlog  SIPO_8BIT1_block.v
vlog  SIPO_16BIT_R.v
vlog  SimpleDualPortRAM_singlebit.v
vlog  HDL_FIFO_L.v
vlog  HDL_FIFO_R.v
vlog  REC_I2S_block.v
vlog  rec_i2s.v
