// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\rec_i2s\rec_i2s.v
// Created: 2023-10-27 19:54:39
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// PARA_OUT_L_0                  ce_out        1
// PARA_OUT_L_1                  ce_out        1
// PARA_OUT_L_2                  ce_out        1
// PARA_OUT_L_3                  ce_out        1
// PARA_OUT_L_4                  ce_out        1
// PARA_OUT_L_5                  ce_out        1
// PARA_OUT_L_6                  ce_out        1
// PARA_OUT_L_7                  ce_out        1
// PARA_OUT_L_8                  ce_out        1
// PARA_OUT_L_9                  ce_out        1
// PARA_OUT_L_10                 ce_out        1
// PARA_OUT_L_11                 ce_out        1
// PARA_OUT_L_12                 ce_out        1
// PARA_OUT_L_13                 ce_out        1
// PARA_OUT_L_14                 ce_out        1
// PARA_OUT_L_15                 ce_out        1
// PARA_OUT_R_0                  ce_out        1
// PARA_OUT_R_1                  ce_out        1
// PARA_OUT_R_2                  ce_out        1
// PARA_OUT_R_3                  ce_out        1
// PARA_OUT_R_4                  ce_out        1
// PARA_OUT_R_5                  ce_out        1
// PARA_OUT_R_6                  ce_out        1
// PARA_OUT_R_7                  ce_out        1
// PARA_OUT_R_8                  ce_out        1
// PARA_OUT_R_9                  ce_out        1
// PARA_OUT_R_10                 ce_out        1
// PARA_OUT_R_11                 ce_out        1
// PARA_OUT_R_12                 ce_out        1
// PARA_OUT_R_13                 ce_out        1
// PARA_OUT_R_14                 ce_out        1
// PARA_OUT_R_15                 ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rec_i2s
// Source Path: rec_i2s
// Hierarchy Level: 0
// Model version: 1.35
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rec_i2s
          (clk,
           reset,
           clk_enable,
           RST,
           LRCLK_IN,
           SDATA_IN,
           ce_out,
           PARA_OUT_L_0,
           PARA_OUT_L_1,
           PARA_OUT_L_2,
           PARA_OUT_L_3,
           PARA_OUT_L_4,
           PARA_OUT_L_5,
           PARA_OUT_L_6,
           PARA_OUT_L_7,
           PARA_OUT_L_8,
           PARA_OUT_L_9,
           PARA_OUT_L_10,
           PARA_OUT_L_11,
           PARA_OUT_L_12,
           PARA_OUT_L_13,
           PARA_OUT_L_14,
           PARA_OUT_L_15,
           PARA_OUT_R_0,
           PARA_OUT_R_1,
           PARA_OUT_R_2,
           PARA_OUT_R_3,
           PARA_OUT_R_4,
           PARA_OUT_R_5,
           PARA_OUT_R_6,
           PARA_OUT_R_7,
           PARA_OUT_R_8,
           PARA_OUT_R_9,
           PARA_OUT_R_10,
           PARA_OUT_R_11,
           PARA_OUT_R_12,
           PARA_OUT_R_13,
           PARA_OUT_R_14,
           PARA_OUT_R_15);


  input   clk;
  input   reset;
  input   clk_enable;
  input   RST;
  input   LRCLK_IN;
  input   SDATA_IN;
  output  ce_out;
  output  [15:0] PARA_OUT_L_0;  // uint16
  output  [15:0] PARA_OUT_L_1;  // uint16
  output  [15:0] PARA_OUT_L_2;  // uint16
  output  [15:0] PARA_OUT_L_3;  // uint16
  output  [15:0] PARA_OUT_L_4;  // uint16
  output  [15:0] PARA_OUT_L_5;  // uint16
  output  [15:0] PARA_OUT_L_6;  // uint16
  output  [15:0] PARA_OUT_L_7;  // uint16
  output  [15:0] PARA_OUT_L_8;  // uint16
  output  [15:0] PARA_OUT_L_9;  // uint16
  output  [15:0] PARA_OUT_L_10;  // uint16
  output  [15:0] PARA_OUT_L_11;  // uint16
  output  [15:0] PARA_OUT_L_12;  // uint16
  output  [15:0] PARA_OUT_L_13;  // uint16
  output  [15:0] PARA_OUT_L_14;  // uint16
  output  [15:0] PARA_OUT_L_15;  // uint16
  output  [15:0] PARA_OUT_R_0;  // uint16
  output  [15:0] PARA_OUT_R_1;  // uint16
  output  [15:0] PARA_OUT_R_2;  // uint16
  output  [15:0] PARA_OUT_R_3;  // uint16
  output  [15:0] PARA_OUT_R_4;  // uint16
  output  [15:0] PARA_OUT_R_5;  // uint16
  output  [15:0] PARA_OUT_R_6;  // uint16
  output  [15:0] PARA_OUT_R_7;  // uint16
  output  [15:0] PARA_OUT_R_8;  // uint16
  output  [15:0] PARA_OUT_R_9;  // uint16
  output  [15:0] PARA_OUT_R_10;  // uint16
  output  [15:0] PARA_OUT_R_11;  // uint16
  output  [15:0] PARA_OUT_R_12;  // uint16
  output  [15:0] PARA_OUT_R_13;  // uint16
  output  [15:0] PARA_OUT_R_14;  // uint16
  output  [15:0] PARA_OUT_R_15;  // uint16


  wire [15:0] REC_I2S_out1_0;  // uint16
  wire [15:0] REC_I2S_out1_1;  // uint16
  wire [15:0] REC_I2S_out1_2;  // uint16
  wire [15:0] REC_I2S_out1_3;  // uint16
  wire [15:0] REC_I2S_out1_4;  // uint16
  wire [15:0] REC_I2S_out1_5;  // uint16
  wire [15:0] REC_I2S_out1_6;  // uint16
  wire [15:0] REC_I2S_out1_7;  // uint16
  wire [15:0] REC_I2S_out1_8;  // uint16
  wire [15:0] REC_I2S_out1_9;  // uint16
  wire [15:0] REC_I2S_out1_10;  // uint16
  wire [15:0] REC_I2S_out1_11;  // uint16
  wire [15:0] REC_I2S_out1_12;  // uint16
  wire [15:0] REC_I2S_out1_13;  // uint16
  wire [15:0] REC_I2S_out1_14;  // uint16
  wire [15:0] REC_I2S_out1_15;  // uint16
  wire [15:0] REC_I2S_out2_0;  // uint16
  wire [15:0] REC_I2S_out2_1;  // uint16
  wire [15:0] REC_I2S_out2_2;  // uint16
  wire [15:0] REC_I2S_out2_3;  // uint16
  wire [15:0] REC_I2S_out2_4;  // uint16
  wire [15:0] REC_I2S_out2_5;  // uint16
  wire [15:0] REC_I2S_out2_6;  // uint16
  wire [15:0] REC_I2S_out2_7;  // uint16
  wire [15:0] REC_I2S_out2_8;  // uint16
  wire [15:0] REC_I2S_out2_9;  // uint16
  wire [15:0] REC_I2S_out2_10;  // uint16
  wire [15:0] REC_I2S_out2_11;  // uint16
  wire [15:0] REC_I2S_out2_12;  // uint16
  wire [15:0] REC_I2S_out2_13;  // uint16
  wire [15:0] REC_I2S_out2_14;  // uint16
  wire [15:0] REC_I2S_out2_15;  // uint16


  REC_I2S_block u_REC_I2S (.clk(clk),
                           .reset(reset),
                           .enb(clk_enable),
                           .RST(RST),
                           .LRCLK_IN(LRCLK_IN),
                           .SDATA_IN(SDATA_IN),
                           .PARA_OUT_L_0(REC_I2S_out1_0),  // uint16
                           .PARA_OUT_L_1(REC_I2S_out1_1),  // uint16
                           .PARA_OUT_L_2(REC_I2S_out1_2),  // uint16
                           .PARA_OUT_L_3(REC_I2S_out1_3),  // uint16
                           .PARA_OUT_L_4(REC_I2S_out1_4),  // uint16
                           .PARA_OUT_L_5(REC_I2S_out1_5),  // uint16
                           .PARA_OUT_L_6(REC_I2S_out1_6),  // uint16
                           .PARA_OUT_L_7(REC_I2S_out1_7),  // uint16
                           .PARA_OUT_L_8(REC_I2S_out1_8),  // uint16
                           .PARA_OUT_L_9(REC_I2S_out1_9),  // uint16
                           .PARA_OUT_L_10(REC_I2S_out1_10),  // uint16
                           .PARA_OUT_L_11(REC_I2S_out1_11),  // uint16
                           .PARA_OUT_L_12(REC_I2S_out1_12),  // uint16
                           .PARA_OUT_L_13(REC_I2S_out1_13),  // uint16
                           .PARA_OUT_L_14(REC_I2S_out1_14),  // uint16
                           .PARA_OUT_L_15(REC_I2S_out1_15),  // uint16
                           .PARA_OUT_R_0(REC_I2S_out2_0),  // uint16
                           .PARA_OUT_R_1(REC_I2S_out2_1),  // uint16
                           .PARA_OUT_R_2(REC_I2S_out2_2),  // uint16
                           .PARA_OUT_R_3(REC_I2S_out2_3),  // uint16
                           .PARA_OUT_R_4(REC_I2S_out2_4),  // uint16
                           .PARA_OUT_R_5(REC_I2S_out2_5),  // uint16
                           .PARA_OUT_R_6(REC_I2S_out2_6),  // uint16
                           .PARA_OUT_R_7(REC_I2S_out2_7),  // uint16
                           .PARA_OUT_R_8(REC_I2S_out2_8),  // uint16
                           .PARA_OUT_R_9(REC_I2S_out2_9),  // uint16
                           .PARA_OUT_R_10(REC_I2S_out2_10),  // uint16
                           .PARA_OUT_R_11(REC_I2S_out2_11),  // uint16
                           .PARA_OUT_R_12(REC_I2S_out2_12),  // uint16
                           .PARA_OUT_R_13(REC_I2S_out2_13),  // uint16
                           .PARA_OUT_R_14(REC_I2S_out2_14),  // uint16
                           .PARA_OUT_R_15(REC_I2S_out2_15)  // uint16
                           );

  assign PARA_OUT_L_0 = REC_I2S_out1_0;

  assign PARA_OUT_L_1 = REC_I2S_out1_1;

  assign PARA_OUT_L_2 = REC_I2S_out1_2;

  assign PARA_OUT_L_3 = REC_I2S_out1_3;

  assign PARA_OUT_L_4 = REC_I2S_out1_4;

  assign PARA_OUT_L_5 = REC_I2S_out1_5;

  assign PARA_OUT_L_6 = REC_I2S_out1_6;

  assign PARA_OUT_L_7 = REC_I2S_out1_7;

  assign PARA_OUT_L_8 = REC_I2S_out1_8;

  assign PARA_OUT_L_9 = REC_I2S_out1_9;

  assign PARA_OUT_L_10 = REC_I2S_out1_10;

  assign PARA_OUT_L_11 = REC_I2S_out1_11;

  assign PARA_OUT_L_12 = REC_I2S_out1_12;

  assign PARA_OUT_L_13 = REC_I2S_out1_13;

  assign PARA_OUT_L_14 = REC_I2S_out1_14;

  assign PARA_OUT_L_15 = REC_I2S_out1_15;

  assign PARA_OUT_R_0 = REC_I2S_out2_0;

  assign PARA_OUT_R_1 = REC_I2S_out2_1;

  assign PARA_OUT_R_2 = REC_I2S_out2_2;

  assign PARA_OUT_R_3 = REC_I2S_out2_3;

  assign PARA_OUT_R_4 = REC_I2S_out2_4;

  assign PARA_OUT_R_5 = REC_I2S_out2_5;

  assign PARA_OUT_R_6 = REC_I2S_out2_6;

  assign PARA_OUT_R_7 = REC_I2S_out2_7;

  assign PARA_OUT_R_8 = REC_I2S_out2_8;

  assign PARA_OUT_R_9 = REC_I2S_out2_9;

  assign PARA_OUT_R_10 = REC_I2S_out2_10;

  assign PARA_OUT_R_11 = REC_I2S_out2_11;

  assign PARA_OUT_R_12 = REC_I2S_out2_12;

  assign PARA_OUT_R_13 = REC_I2S_out2_13;

  assign PARA_OUT_R_14 = REC_I2S_out2_14;

  assign PARA_OUT_R_15 = REC_I2S_out2_15;

  assign ce_out = clk_enable;

endmodule  // rec_i2s

