// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\FPGA_myself\DDS\dds_matlab\hdlsrc\NCO_32\LookUpTableGen.v
// Created: 2023-10-15 20:23:16
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LookUpTableGen
// Source Path: NCO_32/Subsystem/NCO/WaveformGen/LookUpTableGen
// Hierarchy Level: 3
// Model version: 1.7
// 
// Look Up Table Generation Component
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LookUpTableGen
          (clk,
           reset,
           enb,
           lutaddr,
           lutoutput);


  input   clk;
  input   reset;
  input   enb;
  input   [9:0] lutaddr;  // ufix10
  output  signed [15:0] lutoutput;  // sfix16_En14


  reg [9:0] lutaddrInReg;  // ufix10
  wire signed [15:0] lutout;  // sfix16_En14
  reg signed [15:0] lutout_reg;  // sfix16_En14
  reg signed [15:0] lutoutput_1;  // sfix16_En14

  initial begin
    lutaddrInReg = 10'b0000000000;
    lutout_reg = 16'sb0000000000000000;
  end

  // Look up table address input register
  always @(posedge clk)
    begin : LUTaddrRegister_process
      if (enb) begin
        lutaddrInReg <= lutaddr;
      end
    end



  // Quarter sine wave table
  Lookup_Table u_Lookup_Table (.in1(lutaddrInReg),  // ufix10
                               .out(lutout)  // sfix16_En14
                               );

  // Lookup table output register
  always @(posedge clk)
    begin : LUToutResetRegister_process
      if (enb) begin
        lutout_reg <= lutout;
      end
    end



  always @(posedge clk or posedge reset)
    begin : LUToutRegister_process
      if (reset == 1'b1) begin
        lutoutput_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          lutoutput_1 <= lutout_reg;
        end
      end
    end



  assign lutoutput = lutoutput_1;

endmodule  // LookUpTableGen

