// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\nco\subFilter.v
// Created: 2023-09-16 20:49:24
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: subFilter
// Source Path: nco/Subsystem/Discrete FIR Filter/Filter/subFilter
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module subFilter
          (clk,
           reset,
           enb,
           dinReg2_0_re,
           coefIn_0,
           coefIn_1,
           coefIn_2,
           coefIn_3,
           coefIn_4,
           coefIn_5,
           coefIn_6,
           coefIn_7,
           coefIn_8,
           coefIn_9,
           coefIn_10,
           coefIn_11,
           coefIn_12,
           coefIn_13,
           coefIn_14,
           coefIn_15,
           coefIn_16,
           coefIn_17,
           coefIn_18,
           coefIn_19,
           coefIn_20,
           coefIn_21,
           coefIn_22,
           coefIn_23,
           coefIn_24,
           coefIn_25,
           coefIn_26,
           coefIn_27,
           coefIn_28,
           coefIn_29,
           coefIn_30,
           coefIn_31,
           coefIn_32,
           coefIn_33,
           coefIn_34,
           coefIn_35,
           coefIn_36,
           coefIn_37,
           coefIn_38,
           coefIn_39,
           dinRegVld,
           syncReset,
           dout_1_re,
           doutVld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dinReg2_0_re;  // sfix16_En14
  input   signed [15:0] coefIn_0;  // sfix16_En16
  input   signed [15:0] coefIn_1;  // sfix16_En16
  input   signed [15:0] coefIn_2;  // sfix16_En16
  input   signed [15:0] coefIn_3;  // sfix16_En16
  input   signed [15:0] coefIn_4;  // sfix16_En16
  input   signed [15:0] coefIn_5;  // sfix16_En16
  input   signed [15:0] coefIn_6;  // sfix16_En16
  input   signed [15:0] coefIn_7;  // sfix16_En16
  input   signed [15:0] coefIn_8;  // sfix16_En16
  input   signed [15:0] coefIn_9;  // sfix16_En16
  input   signed [15:0] coefIn_10;  // sfix16_En16
  input   signed [15:0] coefIn_11;  // sfix16_En16
  input   signed [15:0] coefIn_12;  // sfix16_En16
  input   signed [15:0] coefIn_13;  // sfix16_En16
  input   signed [15:0] coefIn_14;  // sfix16_En16
  input   signed [15:0] coefIn_15;  // sfix16_En16
  input   signed [15:0] coefIn_16;  // sfix16_En16
  input   signed [15:0] coefIn_17;  // sfix16_En16
  input   signed [15:0] coefIn_18;  // sfix16_En16
  input   signed [15:0] coefIn_19;  // sfix16_En16
  input   signed [15:0] coefIn_20;  // sfix16_En16
  input   signed [15:0] coefIn_21;  // sfix16_En16
  input   signed [15:0] coefIn_22;  // sfix16_En16
  input   signed [15:0] coefIn_23;  // sfix16_En16
  input   signed [15:0] coefIn_24;  // sfix16_En16
  input   signed [15:0] coefIn_25;  // sfix16_En16
  input   signed [15:0] coefIn_26;  // sfix16_En16
  input   signed [15:0] coefIn_27;  // sfix16_En16
  input   signed [15:0] coefIn_28;  // sfix16_En16
  input   signed [15:0] coefIn_29;  // sfix16_En16
  input   signed [15:0] coefIn_30;  // sfix16_En16
  input   signed [15:0] coefIn_31;  // sfix16_En16
  input   signed [15:0] coefIn_32;  // sfix16_En16
  input   signed [15:0] coefIn_33;  // sfix16_En16
  input   signed [15:0] coefIn_34;  // sfix16_En16
  input   signed [15:0] coefIn_35;  // sfix16_En16
  input   signed [15:0] coefIn_36;  // sfix16_En16
  input   signed [15:0] coefIn_37;  // sfix16_En16
  input   signed [15:0] coefIn_38;  // sfix16_En16
  input   signed [15:0] coefIn_39;  // sfix16_En16
  input   dinRegVld;
  input   syncReset;
  output  signed [15:0] dout_1_re;  // sfix16_En12
  output  doutVld;


  reg  [0:43] intdelay_reg;  // ufix1 [44]
  wire [0:43] intdelay_reg_next;  // ufix1 [44]
  wire vldShift;
  wire vldOutTmp;
  wire signed [15:0] ZERO_OUT;  // sfix16_En12
  wire signed [43:0] addin;  // sfix44_En30
  wire signed [15:0] dinDly2;  // sfix16_En14
  wire signed [15:0] dinDly2_1;  // sfix16_En14
  wire signed [43:0] tapout;  // sfix44_En30
  wire signed [15:0] dinDly2_2;  // sfix16_En14
  wire signed [43:0] tapout_1;  // sfix44_En30
  wire signed [15:0] dinDly2_3;  // sfix16_En14
  wire signed [43:0] tapout_2;  // sfix44_En30
  wire signed [15:0] dinDly2_4;  // sfix16_En14
  wire signed [43:0] tapout_3;  // sfix44_En30
  wire signed [15:0] dinDly2_5;  // sfix16_En14
  wire signed [43:0] tapout_4;  // sfix44_En30
  wire signed [15:0] dinDly2_6;  // sfix16_En14
  wire signed [43:0] tapout_5;  // sfix44_En30
  wire signed [15:0] dinDly2_7;  // sfix16_En14
  wire signed [43:0] tapout_6;  // sfix44_En30
  wire signed [15:0] dinDly2_8;  // sfix16_En14
  wire signed [43:0] tapout_7;  // sfix44_En30
  wire signed [15:0] dinDly2_9;  // sfix16_En14
  wire signed [43:0] tapout_8;  // sfix44_En30
  wire signed [15:0] dinDly2_10;  // sfix16_En14
  wire signed [43:0] tapout_9;  // sfix44_En30
  wire signed [15:0] dinDly2_11;  // sfix16_En14
  wire signed [43:0] tapout_10;  // sfix44_En30
  wire signed [15:0] dinDly2_12;  // sfix16_En14
  wire signed [43:0] tapout_11;  // sfix44_En30
  wire signed [15:0] dinDly2_13;  // sfix16_En14
  wire signed [43:0] tapout_12;  // sfix44_En30
  wire signed [15:0] dinDly2_14;  // sfix16_En14
  wire signed [43:0] tapout_13;  // sfix44_En30
  wire signed [15:0] dinDly2_15;  // sfix16_En14
  wire signed [43:0] tapout_14;  // sfix44_En30
  wire signed [15:0] dinDly2_16;  // sfix16_En14
  wire signed [43:0] tapout_15;  // sfix44_En30
  wire signed [15:0] dinDly2_17;  // sfix16_En14
  wire signed [43:0] tapout_16;  // sfix44_En30
  wire signed [15:0] dinDly2_18;  // sfix16_En14
  wire signed [43:0] tapout_17;  // sfix44_En30
  wire signed [15:0] dinDly2_19;  // sfix16_En14
  wire signed [43:0] tapout_18;  // sfix44_En30
  wire signed [15:0] dinDly2_20;  // sfix16_En14
  wire signed [43:0] tapout_19;  // sfix44_En30
  wire signed [15:0] dinDly2_21;  // sfix16_En14
  wire signed [43:0] tapout_20;  // sfix44_En30
  wire signed [15:0] dinDly2_22;  // sfix16_En14
  wire signed [43:0] tapout_21;  // sfix44_En30
  wire signed [15:0] dinDly2_23;  // sfix16_En14
  wire signed [43:0] tapout_22;  // sfix44_En30
  wire signed [15:0] dinDly2_24;  // sfix16_En14
  wire signed [43:0] tapout_23;  // sfix44_En30
  wire signed [15:0] dinDly2_25;  // sfix16_En14
  wire signed [43:0] tapout_24;  // sfix44_En30
  wire signed [15:0] dinDly2_26;  // sfix16_En14
  wire signed [43:0] tapout_25;  // sfix44_En30
  wire signed [15:0] dinDly2_27;  // sfix16_En14
  wire signed [43:0] tapout_26;  // sfix44_En30
  wire signed [15:0] dinDly2_28;  // sfix16_En14
  wire signed [43:0] tapout_27;  // sfix44_En30
  wire signed [15:0] dinDly2_29;  // sfix16_En14
  wire signed [43:0] tapout_28;  // sfix44_En30
  wire signed [15:0] dinDly2_30;  // sfix16_En14
  wire signed [43:0] tapout_29;  // sfix44_En30
  wire signed [15:0] dinDly2_31;  // sfix16_En14
  wire signed [43:0] tapout_30;  // sfix44_En30
  wire signed [15:0] dinDly2_32;  // sfix16_En14
  wire signed [43:0] tapout_31;  // sfix44_En30
  wire signed [15:0] dinDly2_33;  // sfix16_En14
  wire signed [43:0] tapout_32;  // sfix44_En30
  wire signed [15:0] dinDly2_34;  // sfix16_En14
  wire signed [43:0] tapout_33;  // sfix44_En30
  wire signed [15:0] dinDly2_35;  // sfix16_En14
  wire signed [43:0] tapout_34;  // sfix44_En30
  wire signed [15:0] dinDly2_36;  // sfix16_En14
  wire signed [43:0] tapout_35;  // sfix44_En30
  wire signed [15:0] dinDly2_37;  // sfix16_En14
  wire signed [43:0] tapout_36;  // sfix44_En30
  wire signed [15:0] dinDly2_38;  // sfix16_En14
  wire signed [43:0] tapout_37;  // sfix44_En30
  wire signed [15:0] dinDly2_39;  // sfix16_En14
  wire signed [43:0] tapout_38;  // sfix44_En30
  wire signed [43:0] tapout_39;  // sfix44_En30
  reg signed [43:0] foutDly;  // sfix44_En30
  wire signed [15:0] dout_cast;  // sfix16_En12
  wire signed [15:0] muxOut;  // sfix16_En12
  reg signed [15:0] dout_1_re_1;  // sfix16_En12
  reg  doutVld_1;


  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        intdelay_reg[0] <= 1'b0;
        intdelay_reg[1] <= 1'b0;
        intdelay_reg[2] <= 1'b0;
        intdelay_reg[3] <= 1'b0;
        intdelay_reg[4] <= 1'b0;
        intdelay_reg[5] <= 1'b0;
        intdelay_reg[6] <= 1'b0;
        intdelay_reg[7] <= 1'b0;
        intdelay_reg[8] <= 1'b0;
        intdelay_reg[9] <= 1'b0;
        intdelay_reg[10] <= 1'b0;
        intdelay_reg[11] <= 1'b0;
        intdelay_reg[12] <= 1'b0;
        intdelay_reg[13] <= 1'b0;
        intdelay_reg[14] <= 1'b0;
        intdelay_reg[15] <= 1'b0;
        intdelay_reg[16] <= 1'b0;
        intdelay_reg[17] <= 1'b0;
        intdelay_reg[18] <= 1'b0;
        intdelay_reg[19] <= 1'b0;
        intdelay_reg[20] <= 1'b0;
        intdelay_reg[21] <= 1'b0;
        intdelay_reg[22] <= 1'b0;
        intdelay_reg[23] <= 1'b0;
        intdelay_reg[24] <= 1'b0;
        intdelay_reg[25] <= 1'b0;
        intdelay_reg[26] <= 1'b0;
        intdelay_reg[27] <= 1'b0;
        intdelay_reg[28] <= 1'b0;
        intdelay_reg[29] <= 1'b0;
        intdelay_reg[30] <= 1'b0;
        intdelay_reg[31] <= 1'b0;
        intdelay_reg[32] <= 1'b0;
        intdelay_reg[33] <= 1'b0;
        intdelay_reg[34] <= 1'b0;
        intdelay_reg[35] <= 1'b0;
        intdelay_reg[36] <= 1'b0;
        intdelay_reg[37] <= 1'b0;
        intdelay_reg[38] <= 1'b0;
        intdelay_reg[39] <= 1'b0;
        intdelay_reg[40] <= 1'b0;
        intdelay_reg[41] <= 1'b0;
        intdelay_reg[42] <= 1'b0;
        intdelay_reg[43] <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            intdelay_reg[0] <= 1'b0;
            intdelay_reg[1] <= 1'b0;
            intdelay_reg[2] <= 1'b0;
            intdelay_reg[3] <= 1'b0;
            intdelay_reg[4] <= 1'b0;
            intdelay_reg[5] <= 1'b0;
            intdelay_reg[6] <= 1'b0;
            intdelay_reg[7] <= 1'b0;
            intdelay_reg[8] <= 1'b0;
            intdelay_reg[9] <= 1'b0;
            intdelay_reg[10] <= 1'b0;
            intdelay_reg[11] <= 1'b0;
            intdelay_reg[12] <= 1'b0;
            intdelay_reg[13] <= 1'b0;
            intdelay_reg[14] <= 1'b0;
            intdelay_reg[15] <= 1'b0;
            intdelay_reg[16] <= 1'b0;
            intdelay_reg[17] <= 1'b0;
            intdelay_reg[18] <= 1'b0;
            intdelay_reg[19] <= 1'b0;
            intdelay_reg[20] <= 1'b0;
            intdelay_reg[21] <= 1'b0;
            intdelay_reg[22] <= 1'b0;
            intdelay_reg[23] <= 1'b0;
            intdelay_reg[24] <= 1'b0;
            intdelay_reg[25] <= 1'b0;
            intdelay_reg[26] <= 1'b0;
            intdelay_reg[27] <= 1'b0;
            intdelay_reg[28] <= 1'b0;
            intdelay_reg[29] <= 1'b0;
            intdelay_reg[30] <= 1'b0;
            intdelay_reg[31] <= 1'b0;
            intdelay_reg[32] <= 1'b0;
            intdelay_reg[33] <= 1'b0;
            intdelay_reg[34] <= 1'b0;
            intdelay_reg[35] <= 1'b0;
            intdelay_reg[36] <= 1'b0;
            intdelay_reg[37] <= 1'b0;
            intdelay_reg[38] <= 1'b0;
            intdelay_reg[39] <= 1'b0;
            intdelay_reg[40] <= 1'b0;
            intdelay_reg[41] <= 1'b0;
            intdelay_reg[42] <= 1'b0;
            intdelay_reg[43] <= 1'b0;
          end
          else begin
            if (dinRegVld) begin
              intdelay_reg[0] <= intdelay_reg_next[0];
              intdelay_reg[1] <= intdelay_reg_next[1];
              intdelay_reg[2] <= intdelay_reg_next[2];
              intdelay_reg[3] <= intdelay_reg_next[3];
              intdelay_reg[4] <= intdelay_reg_next[4];
              intdelay_reg[5] <= intdelay_reg_next[5];
              intdelay_reg[6] <= intdelay_reg_next[6];
              intdelay_reg[7] <= intdelay_reg_next[7];
              intdelay_reg[8] <= intdelay_reg_next[8];
              intdelay_reg[9] <= intdelay_reg_next[9];
              intdelay_reg[10] <= intdelay_reg_next[10];
              intdelay_reg[11] <= intdelay_reg_next[11];
              intdelay_reg[12] <= intdelay_reg_next[12];
              intdelay_reg[13] <= intdelay_reg_next[13];
              intdelay_reg[14] <= intdelay_reg_next[14];
              intdelay_reg[15] <= intdelay_reg_next[15];
              intdelay_reg[16] <= intdelay_reg_next[16];
              intdelay_reg[17] <= intdelay_reg_next[17];
              intdelay_reg[18] <= intdelay_reg_next[18];
              intdelay_reg[19] <= intdelay_reg_next[19];
              intdelay_reg[20] <= intdelay_reg_next[20];
              intdelay_reg[21] <= intdelay_reg_next[21];
              intdelay_reg[22] <= intdelay_reg_next[22];
              intdelay_reg[23] <= intdelay_reg_next[23];
              intdelay_reg[24] <= intdelay_reg_next[24];
              intdelay_reg[25] <= intdelay_reg_next[25];
              intdelay_reg[26] <= intdelay_reg_next[26];
              intdelay_reg[27] <= intdelay_reg_next[27];
              intdelay_reg[28] <= intdelay_reg_next[28];
              intdelay_reg[29] <= intdelay_reg_next[29];
              intdelay_reg[30] <= intdelay_reg_next[30];
              intdelay_reg[31] <= intdelay_reg_next[31];
              intdelay_reg[32] <= intdelay_reg_next[32];
              intdelay_reg[33] <= intdelay_reg_next[33];
              intdelay_reg[34] <= intdelay_reg_next[34];
              intdelay_reg[35] <= intdelay_reg_next[35];
              intdelay_reg[36] <= intdelay_reg_next[36];
              intdelay_reg[37] <= intdelay_reg_next[37];
              intdelay_reg[38] <= intdelay_reg_next[38];
              intdelay_reg[39] <= intdelay_reg_next[39];
              intdelay_reg[40] <= intdelay_reg_next[40];
              intdelay_reg[41] <= intdelay_reg_next[41];
              intdelay_reg[42] <= intdelay_reg_next[42];
              intdelay_reg[43] <= intdelay_reg_next[43];
            end
          end
        end
      end
    end

  assign vldShift = intdelay_reg[43];
  assign intdelay_reg_next[0] = dinRegVld;
  assign intdelay_reg_next[1] = intdelay_reg[0];
  assign intdelay_reg_next[2] = intdelay_reg[1];
  assign intdelay_reg_next[3] = intdelay_reg[2];
  assign intdelay_reg_next[4] = intdelay_reg[3];
  assign intdelay_reg_next[5] = intdelay_reg[4];
  assign intdelay_reg_next[6] = intdelay_reg[5];
  assign intdelay_reg_next[7] = intdelay_reg[6];
  assign intdelay_reg_next[8] = intdelay_reg[7];
  assign intdelay_reg_next[9] = intdelay_reg[8];
  assign intdelay_reg_next[10] = intdelay_reg[9];
  assign intdelay_reg_next[11] = intdelay_reg[10];
  assign intdelay_reg_next[12] = intdelay_reg[11];
  assign intdelay_reg_next[13] = intdelay_reg[12];
  assign intdelay_reg_next[14] = intdelay_reg[13];
  assign intdelay_reg_next[15] = intdelay_reg[14];
  assign intdelay_reg_next[16] = intdelay_reg[15];
  assign intdelay_reg_next[17] = intdelay_reg[16];
  assign intdelay_reg_next[18] = intdelay_reg[17];
  assign intdelay_reg_next[19] = intdelay_reg[18];
  assign intdelay_reg_next[20] = intdelay_reg[19];
  assign intdelay_reg_next[21] = intdelay_reg[20];
  assign intdelay_reg_next[22] = intdelay_reg[21];
  assign intdelay_reg_next[23] = intdelay_reg[22];
  assign intdelay_reg_next[24] = intdelay_reg[23];
  assign intdelay_reg_next[25] = intdelay_reg[24];
  assign intdelay_reg_next[26] = intdelay_reg[25];
  assign intdelay_reg_next[27] = intdelay_reg[26];
  assign intdelay_reg_next[28] = intdelay_reg[27];
  assign intdelay_reg_next[29] = intdelay_reg[28];
  assign intdelay_reg_next[30] = intdelay_reg[29];
  assign intdelay_reg_next[31] = intdelay_reg[30];
  assign intdelay_reg_next[32] = intdelay_reg[31];
  assign intdelay_reg_next[33] = intdelay_reg[32];
  assign intdelay_reg_next[34] = intdelay_reg[33];
  assign intdelay_reg_next[35] = intdelay_reg[34];
  assign intdelay_reg_next[36] = intdelay_reg[35];
  assign intdelay_reg_next[37] = intdelay_reg[36];
  assign intdelay_reg_next[38] = intdelay_reg[37];
  assign intdelay_reg_next[39] = intdelay_reg[38];
  assign intdelay_reg_next[40] = intdelay_reg[39];
  assign intdelay_reg_next[41] = intdelay_reg[40];
  assign intdelay_reg_next[42] = intdelay_reg[41];
  assign intdelay_reg_next[43] = intdelay_reg[42];



  assign vldOutTmp = dinRegVld & vldShift;



  assign ZERO_OUT = 16'sb0000000000000000;



  assign addin = 44'sh00000000000;



  FilterTapSystolicPreAddWvlIn u_FilterTap_1 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinReg2_0_re),  // sfix16_En14
                                              .dinPreAdd(dinDly2),  // sfix16_En14
                                              .coefIn_0(coefIn_0),  // sfix16_En16
                                              .addin(addin),  // sfix44_En30
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_1),  // sfix16_En14
                                              .tapout(tapout)  // sfix44_En30
                                              );

  FilterTapSystolicPreAddWvlIn u_FilterTap_2 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_1),  // sfix16_En14
                                              .dinPreAdd(dinDly2),  // sfix16_En14
                                              .coefIn_0(coefIn_1),  // sfix16_En16
                                              .addin(tapout),  // sfix44_En30
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_2),  // sfix16_En14
                                              .tapout(tapout_1)  // sfix44_En30
                                              );

  FilterTapSystolicPreAddWvlIn u_FilterTap_3 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_2),  // sfix16_En14
                                              .dinPreAdd(dinDly2),  // sfix16_En14
                                              .coefIn_0(coefIn_2),  // sfix16_En16
                                              .addin(tapout_1),  // sfix44_En30
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_3),  // sfix16_En14
                                              .tapout(tapout_2)  // sfix44_En30
                                              );

  FilterTapSystolicPreAddWvlIn u_FilterTap_4 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_3),  // sfix16_En14
                                              .dinPreAdd(dinDly2),  // sfix16_En14
                                              .coefIn_0(coefIn_3),  // sfix16_En16
                                              .addin(tapout_2),  // sfix44_En30
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_4),  // sfix16_En14
                                              .tapout(tapout_3)  // sfix44_En30
                                              );

  FilterTapSystolicPreAddWvlIn u_FilterTap_5 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_4),  // sfix16_En14
                                              .dinPreAdd(dinDly2),  // sfix16_En14
                                              .coefIn_0(coefIn_4),  // sfix16_En16
                                              .addin(tapout_3),  // sfix44_En30
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_5),  // sfix16_En14
                                              .tapout(tapout_4)  // sfix44_En30
                                              );

  FilterTapSystolicPreAddWvlIn u_FilterTap_6 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_5),  // sfix16_En14
                                              .dinPreAdd(dinDly2),  // sfix16_En14
                                              .coefIn_0(coefIn_5),  // sfix16_En16
                                              .addin(tapout_4),  // sfix44_En30
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_6),  // sfix16_En14
                                              .tapout(tapout_5)  // sfix44_En30
                                              );

  FilterTapSystolicPreAddWvlIn u_FilterTap_7 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_6),  // sfix16_En14
                                              .dinPreAdd(dinDly2),  // sfix16_En14
                                              .coefIn_0(coefIn_6),  // sfix16_En16
                                              .addin(tapout_5),  // sfix44_En30
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_7),  // sfix16_En14
                                              .tapout(tapout_6)  // sfix44_En30
                                              );

  FilterTapSystolicPreAddWvlIn u_FilterTap_8 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_7),  // sfix16_En14
                                              .dinPreAdd(dinDly2),  // sfix16_En14
                                              .coefIn_0(coefIn_7),  // sfix16_En16
                                              .addin(tapout_6),  // sfix44_En30
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_8),  // sfix16_En14
                                              .tapout(tapout_7)  // sfix44_En30
                                              );

  FilterTapSystolicPreAddWvlIn u_FilterTap_9 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_8),  // sfix16_En14
                                              .dinPreAdd(dinDly2),  // sfix16_En14
                                              .coefIn_0(coefIn_8),  // sfix16_En16
                                              .addin(tapout_7),  // sfix44_En30
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_9),  // sfix16_En14
                                              .tapout(tapout_8)  // sfix44_En30
                                              );

  FilterTapSystolicPreAddWvlIn u_FilterTap_10 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_9),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_9),  // sfix16_En16
                                               .addin(tapout_8),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_10),  // sfix16_En14
                                               .tapout(tapout_9)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_11 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_10),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_10),  // sfix16_En16
                                               .addin(tapout_9),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_11),  // sfix16_En14
                                               .tapout(tapout_10)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_12 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_11),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_11),  // sfix16_En16
                                               .addin(tapout_10),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_12),  // sfix16_En14
                                               .tapout(tapout_11)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_13 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_12),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_12),  // sfix16_En16
                                               .addin(tapout_11),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_13),  // sfix16_En14
                                               .tapout(tapout_12)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_14 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_13),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_13),  // sfix16_En16
                                               .addin(tapout_12),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_14),  // sfix16_En14
                                               .tapout(tapout_13)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_15 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_14),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_14),  // sfix16_En16
                                               .addin(tapout_13),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_15),  // sfix16_En14
                                               .tapout(tapout_14)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_16 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_15),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_15),  // sfix16_En16
                                               .addin(tapout_14),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_16),  // sfix16_En14
                                               .tapout(tapout_15)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_17 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_16),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_16),  // sfix16_En16
                                               .addin(tapout_15),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_17),  // sfix16_En14
                                               .tapout(tapout_16)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_18 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_17),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_17),  // sfix16_En16
                                               .addin(tapout_16),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_18),  // sfix16_En14
                                               .tapout(tapout_17)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_19 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_18),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_18),  // sfix16_En16
                                               .addin(tapout_17),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_19),  // sfix16_En14
                                               .tapout(tapout_18)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_20 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_19),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_19),  // sfix16_En16
                                               .addin(tapout_18),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_20),  // sfix16_En14
                                               .tapout(tapout_19)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_21 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_20),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_20),  // sfix16_En16
                                               .addin(tapout_19),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_21),  // sfix16_En14
                                               .tapout(tapout_20)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_22 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_21),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_21),  // sfix16_En16
                                               .addin(tapout_20),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_22),  // sfix16_En14
                                               .tapout(tapout_21)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_23 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_22),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_22),  // sfix16_En16
                                               .addin(tapout_21),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_23),  // sfix16_En14
                                               .tapout(tapout_22)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_24 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_23),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_23),  // sfix16_En16
                                               .addin(tapout_22),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_24),  // sfix16_En14
                                               .tapout(tapout_23)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_25 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_24),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_24),  // sfix16_En16
                                               .addin(tapout_23),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_25),  // sfix16_En14
                                               .tapout(tapout_24)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_26 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_25),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_25),  // sfix16_En16
                                               .addin(tapout_24),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_26),  // sfix16_En14
                                               .tapout(tapout_25)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_27 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_26),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_26),  // sfix16_En16
                                               .addin(tapout_25),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_27),  // sfix16_En14
                                               .tapout(tapout_26)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_28 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_27),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_27),  // sfix16_En16
                                               .addin(tapout_26),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_28),  // sfix16_En14
                                               .tapout(tapout_27)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_29 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_28),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_28),  // sfix16_En16
                                               .addin(tapout_27),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_29),  // sfix16_En14
                                               .tapout(tapout_28)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_30 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_29),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_29),  // sfix16_En16
                                               .addin(tapout_28),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_30),  // sfix16_En14
                                               .tapout(tapout_29)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_31 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_30),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_30),  // sfix16_En16
                                               .addin(tapout_29),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_31),  // sfix16_En14
                                               .tapout(tapout_30)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_32 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_31),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_31),  // sfix16_En16
                                               .addin(tapout_30),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_32),  // sfix16_En14
                                               .tapout(tapout_31)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_33 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_32),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_32),  // sfix16_En16
                                               .addin(tapout_31),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_33),  // sfix16_En14
                                               .tapout(tapout_32)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_34 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_33),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_33),  // sfix16_En16
                                               .addin(tapout_32),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_34),  // sfix16_En14
                                               .tapout(tapout_33)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_35 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_34),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_34),  // sfix16_En16
                                               .addin(tapout_33),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_35),  // sfix16_En14
                                               .tapout(tapout_34)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_36 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_35),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_35),  // sfix16_En16
                                               .addin(tapout_34),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_36),  // sfix16_En14
                                               .tapout(tapout_35)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_37 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_36),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_36),  // sfix16_En16
                                               .addin(tapout_35),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_37),  // sfix16_En14
                                               .tapout(tapout_36)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_38 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_37),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_37),  // sfix16_En16
                                               .addin(tapout_36),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_38),  // sfix16_En14
                                               .tapout(tapout_37)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_39 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_38),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_38),  // sfix16_En16
                                               .addin(tapout_37),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_39),  // sfix16_En14
                                               .tapout(tapout_38)  // sfix44_En30
                                               );

  FilterTapSystolicPreAddWvlIn u_FilterTap_40 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_39),  // sfix16_En14
                                               .dinPreAdd(dinDly2),  // sfix16_En14
                                               .coefIn_0(coefIn_39),  // sfix16_En16
                                               .addin(tapout_38),  // sfix44_En30
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2),  // sfix16_En14
                                               .tapout(tapout_39)  // sfix44_En30
                                               );

  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        foutDly <= 44'sh00000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            foutDly <= 44'sh00000000000;
          end
          else begin
            if (dinRegVld) begin
              foutDly <= tapout_39;
            end
          end
        end
      end
    end



  assign dout_cast = foutDly[33:18];



  assign muxOut = (vldOutTmp == 1'b0 ? ZERO_OUT :
              dout_cast);



  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        dout_1_re_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dout_1_re_1 <= 16'sb0000000000000000;
          end
          else begin
            dout_1_re_1 <= muxOut;
          end
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        doutVld_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            doutVld_1 <= 1'b0;
          end
          else begin
            doutVld_1 <= vldOutTmp;
          end
        end
      end
    end



  assign dout_1_re = dout_1_re_1;

  assign doutVld = doutVld_1;

endmodule  // subFilter

