vlib work
vlog  SIPO_2BIT.v
vlog  SIPO_2BIT1.v
vlog  SIPO_4BIT.v
vlog  SIPO_2BIT_block.v
vlog  SIPO_2BIT1_block.v
vlog  SIPO_4BIT1.v
vlog  SIPO_8BIT.v
vlog  SIPO_2BIT_block1.v
vlog  SIPO_2BIT1_block1.v
vlog  SIPO_4BIT_block.v
vlog  SIPO_2BIT_block2.v
vlog  SIPO_2BIT1_block2.v
vlog  SIPO_4BIT1_block.v
vlog  SIPO_8BIT1.v
vlog  SIPO_16BIT.v
vlog  SIPO_2BIT_block3.v
vlog  SIPO_2BIT1_block3.v
vlog  SIPO_4BIT_block1.v
vlog  SIPO_2BIT_block4.v
vlog  SIPO_2BIT1_block4.v
vlog  SIPO_4BIT1_block1.v
vlog  SIPO_8BIT_block.v
vlog  SIPO_2BIT_block5.v
vlog  SIPO_2BIT1_block5.v
vlog  SIPO_4BIT_block2.v
vlog  SIPO_2BIT_block6.v
vlog  SIPO_2BIT1_block6.v
vlog  SIPO_4BIT1_block2.v
vlog  SIPO_8BIT1_block.v
vlog  SIPO_16BIT1.v
vlog  Subsystem.v
vlog  SIPO_2BIT_block7.v
vlog  SIPO_2BIT1_block7.v
vlog  SIPO_4BIT_block3.v
vlog  SIPO_2BIT_block8.v
vlog  SIPO_2BIT1_block8.v
vlog  SIPO_4BIT1_block3.v
vlog  SIPO_8BIT_block1.v
vlog  SIPO_2BIT_block9.v
vlog  SIPO_2BIT1_block9.v
vlog  SIPO_4BIT_block4.v
vlog  SIPO_2BIT_block10.v
vlog  SIPO_2BIT1_block10.v
vlog  SIPO_4BIT1_block4.v
vlog  SIPO_8BIT1_block1.v
vlog  SIPO_16BIT_block.v
vlog  SIPO_2BIT_block11.v
vlog  SIPO_2BIT1_block11.v
vlog  SIPO_4BIT_block5.v
vlog  SIPO_2BIT_block12.v
vlog  SIPO_2BIT1_block12.v
vlog  SIPO_4BIT1_block5.v
vlog  SIPO_8BIT_block2.v
vlog  SIPO_2BIT_block13.v
vlog  SIPO_2BIT1_block13.v
vlog  SIPO_4BIT_block6.v
vlog  SIPO_2BIT_block14.v
vlog  SIPO_2BIT1_block14.v
vlog  SIPO_4BIT1_block6.v
vlog  SIPO_8BIT1_block2.v
vlog  SIPO_16BIT1_block.v
vlog  Subsystem1.v
vlog  REC_I2S_NOFIFO.v
