// -------------------------------------------------------------
// 
// File Name: F:\Git_Repository\FPGA_myself\DDS\I2S\REC_I2S\fifo_trigger\hdlsrc\rec_i2s\SIPO_2BIT1_block3.v
// Created: 2023-10-29 14:30:23
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SIPO_2BIT1_block3
// Source Path: rec_i2s/REC_I2S_NOFIFO/Subsystem/SIPO_16BIT1/SIPO_8BIT/SIPO_4BIT/SIPO_2BIT1
// Hierarchy Level: 5
// Model version: 1.58
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SIPO_2BIT1_block3
          (clk,
           reset,
           enb,
           SERIAL_IN,
           ENABLE,
           PARA_OUT_signal1,
           PARA_OUT_signal2,
           SERIAL_OUT);


  input   clk;
  input   reset;
  input   enb;
  input   SERIAL_IN;
  input   ENABLE;
  output  PARA_OUT_signal1;
  output  PARA_OUT_signal2;
  output  SERIAL_OUT;


  reg  Delay_bypass_delay;  // ufix1
  reg  Delay_reg;  // ufix1
  wire Delay_out1;
  reg  Delay1_bypass_delay;  // ufix1
  reg  Delay1_reg;  // ufix1
  wire Delay1_out1;


  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_bypass_delay <= 1'b0;
        Delay_reg <= 1'b0;
      end
      else begin
        if (enb && ENABLE) begin
          Delay_bypass_delay <= Delay_reg;
          Delay_reg <= SERIAL_IN;
        end
      end
    end

  assign Delay_out1 = (ENABLE == 1'b1 ? Delay_reg :
              Delay_bypass_delay);



  always @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_bypass_delay <= 1'b0;
        Delay1_reg <= 1'b0;
      end
      else begin
        if (enb && ENABLE) begin
          Delay1_bypass_delay <= Delay1_reg;
          Delay1_reg <= Delay_out1;
        end
      end
    end

  assign Delay1_out1 = (ENABLE == 1'b1 ? Delay1_reg :
              Delay1_bypass_delay);



  assign PARA_OUT_signal1 = Delay1_out1;

  assign PARA_OUT_signal2 = Delay_out1;

  assign SERIAL_OUT = Delay1_out1;

endmodule  // SIPO_2BIT1_block3

