vlib work
vlog  SIPO_2BIT.v
vlog  SIPO_2BIT1.v
vlog  SIPO_4BIT.v
vlog  SIPO_2BIT_block.v
vlog  SIPO_2BIT1_block.v
vlog  SIPO_4BIT1.v
vlog  SIPO_8BIT.v
vlog  SIPO_2BIT_block1.v
vlog  SIPO_2BIT1_block1.v
vlog  SIPO_4BIT_block.v
vlog  SIPO_2BIT_block2.v
vlog  SIPO_2BIT1_block2.v
vlog  SIPO_4BIT1_block.v
vlog  SIPO_8BIT1.v
vlog  SIPO_16BIT.v
